### DISCUSSION TITLE
How to enable https?

### DISCUSSION THREAD

**Discussion by yongpro** [docker-library/wordpress#668] [General]
Hi,

I use wordpress of docker version normally, now want to enable https. Do we have guide to enable that?  Follow my now config:

```
[root@xxxxxxx my_wordpress]# more docker-compose.yml
version: '3'
 
services:
   db:
     image: mysql:5.7
     volumes:
       - ./mysql_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: xxxx
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
 
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./wordpress_data:/var/www/html
     ports:
       - "80:80"
     dns:
       - 1.0.0.1
       - 8.8.8.8
     restart: always
     environment:
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

volumes:
    db_data:
```
