### DISCUSSION TITLE
Has anyone set this up with PHP 8.1?

### DISCUSSION THREAD

**Discussion by Zegnat** [docker-library/wordpress#677] [General]
When I try to run with `wordpress:5.8.3-php8.1` as my image, instead of being redirected to /wp-admin/install.php on first navigation, it throws a fatal error:

```
Fatal error: Uncaught mysqli_sql_exception: Table 'wordpress.wp_options' doesn't exist in /var/www/html/wp-includes/wp-db.php:2056
```

This seems to be isolated to PHP 8.1, as dropping my image down to `wordpress:5.8.3-php8.0` gets me passed the error and onto the installation screen.

Any ideas what might be causing that? I am new to running WordPress in Docker so I do not want to exclude user error...

If you want to reproduce the error, you can use `docker-compose`:

```yaml
version: '3'

services:
  database:
    image: mariadb:10.6.5
    restart: unless-stopped
    volumes:
      - database-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
    networks:
      - wordpress
  web:
    image: wordpress:5.8.3-php8.1
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
      WORDPRESS_DEBUG: 1
    ports:
      - 80:80
    depends_on:
      - database
    networks:
      - wordpress

networks:
  wordpress:

volumes:
  database-volume:
```
