### DISCUSSION TITLE
Apache 403 Forbidden on wp-admin

### DISCUSSION THREAD

**Discussion by oxr463** [docker-library/wordpress#679] [General]
> Forbidden
>
> You don't have permission to access this resource.
> Apache/2.4.38 (Debian) Server at wordpress.com Port 80

URL: http://wordpress.com/wp-admin/

Here is my `docker-compose.yml` file:

```
version: '3.1'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt/:/etc/letsencrypt
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: always
  wordpress:
    container_name: wordpress
    image: wordpress:5.6.1-php7.3-apache
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: bar
      WORDPRESS_DB_PASSWORD: baz
      WORDPRESS_DB_NAME: foo
    volumes:
      - wordpress:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: foo
      MYSQL_USER: bar
      MYSQL_PASSWORD: baz
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    command: --max_allowed_packet=500M
volumes:
  wordpress:
  db:
```

Here is my `nginx.conf` file:

```
worker_processes 1;

events {
  worker_connections 4096;
}

http {
  error_log stderr debug;

  server {
    server_name wordpress.com;

    location / {
      client_body_buffer_size 1024k;
      client_max_body_size 500M;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header Host $host;
      proxy_pass http://wordpress:80;
      proxy_redirect off;
      access_log /var/log/nginx-access.log combined;
    }

    location /.well-known/acme-challenge/ {
      root /var/www/certbot;
    }

    listen 80;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/wordpress.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wordpress.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
  }
}
```
