### DISCUSSION TITLE
Arabic language cannot be activated

### DISCUSSION THREAD

**Discussion by codeline-ae** [docker-library/wordpress#719] [General]
Hi, 

I have been facing this issue that I cant make sense of. So, using a clean installation of wordpress:6.0-php8.1-apache, after finishing installation, I tried change the website language to Arabic (العربية), but as soon as I did this, the website stopped working with an error asking to visit this link: https://wordpress.org/support/article/faq-troubleshooting/

I went through the container logs and I found the following

`PHP Fatal error:  Uncaught ValueError: Missing format specifier at end of string in /var/www/html/wp-includes/script-loader.php:1271\nStack trace:\n#0 /var/www/html/wp-includes/script-loader.php(1271): sprintf('\\xD8\\xAA\\xD9\\x87\\xD8\\xA7\\xD9\\x86\\xD9\\x8A\\xD9\\x86\\xD8\\xA7!...', 'https://wordpre...', '<button type="b...')\n#1 /var/www/html/wp-includes/class-wp-hook.php(307): wp_default_scripts(Object(WP_Scripts))\n#2 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)\n#3 /var/www/html/wp-includes/plugin.php(524): WP_Hook->do_action(Array)\n#4 /var/www/html/wp-includes/class.wp-scripts.php(167): do_action_ref_array('wp_default_scri...', Array)\n#5 /var/www/html/wp-includes/class.wp-scripts.php(142): WP_Scripts->init()\n#6 /var/www/html/wp-includes/functions.wp-scripts.php(24): WP_Scripts->__construct()\n#7 /var/www/html/wp-includes/functions.wp-scripts.php(147): wp_scripts()\n#8 /var/www/html/wp-includes/widgets/class-wp-widget-text.php(59): wp_add_inline_script('text-widgets', 'wp.textWidgets....')\n#9 /var/www/html/wp-includes/class-wp-widget.php(274): WP_Widget_Text->_register_one()\n#10 /var/www/html/wp-includes/class-wp-widget-factory.php(102): WP_Widget->_register()\n#11 /var/www/html/wp-includes/class-wp-hook.php(307): WP_Widget_Factory->_register_widgets('')\n#12 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)\n#13 /var/www/html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)\n#14 /var/www/html/wp-includes/widgets.php(1854): do_action('widgets_init')\n#15 /var/www/html/wp-includes/class-wp-hook.php(307): wp_widgets_init('')\n#16 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)\n#17 /var/www/html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)\n#18 /var/www/html/wp-settings.php(598): do_action('init')\n#19 /var/www/html/wp-config.php(96): require_once('/var/www/html/w...')\n#20 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')\n#21 /var/www/html/wp-admin/admin-ajax.php(22): require_once('/var/www/html/w...')\n#22 {main}\n  thrown in /var/www/html/wp-includes/script-loader.php on line 1271, referer: http://localhost/wp-admin/options-general.php`

My guess is, there is something wrong the language file Encoding. I am not sure through.

Any input?

**Comment by wglambert** [comment]
I don't run into any issues using Arabic as the default language it's initialized with
![image](https://user-images.githubusercontent.com/26428991/171229003-4c409680-d65b-4e31-991d-569b9fb7cdea.png)

And initializing it in English and then selecting Arabic works without issue
![image](https://user-images.githubusercontent.com/26428991/171229514-dbffb21e-887f-449f-8bac-ef83ecd0d34e.png)


The docker-compose file
```yml
version: '3.1'

services:

  wordpress:
    image: wordpress:6.0-php8.1-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
```
