### DISCUSSION TITLE
Example docker-compose.yml not working (port mapping + loopback)

### DISCUSSION THREAD

**Discussion by jonaaix** [docker-library/wordpress#721] [General]
As mentioned in some earlier issues (#611, #493, #480), the given `docker-compose.yml` on [hub.docker.com](https://hub.docker.com/_/wordpress?tab=description) with port mapping `8080:80` does not work, because the port mapping itself breaks the loopback, resulting in two critical errors:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/15804690/172018476-276438e8-610e-4694-a91f-ed8af15935b6.png">
<img width="821" alt="image" src="https://user-images.githubusercontent.com/15804690/172018439-e5fb2f92-cf94-448a-a6ab-597459378dc1.png">

So it should be either added a necessary step to fix this issue with port mapping (which I am currently not aware of), or it should be changed to `port 80:80`, which currently solves the issue, mentioning that other port mappings currently will not work.

**Comment by wglambert** [comment]
I'm not able to reproduce
![image](https://user-images.githubusercontent.com/26428991/172205613-783d831d-7d33-43e4-a5c6-395611864262.png)
![image](https://user-images.githubusercontent.com/26428991/172206395-66656069-5e4f-43f2-8abd-5f56df0a3ba9.png)



Using the docker-compose.yml from https://github.com/docker-library/docs/tree/master/wordpress#-via-docker-stack-deploy-or-docker-compose

**Comment by jonaaix** [comment]
I'm using MacOS 12.4, already disabled the firewall, tried different browsers. 
Below is my compose file, just using a different DB. Using Network or Docker Volumes makes no difference.

```yml
version: '3.1'

services:
  mariadb:
      container_name: APP_mariadb
      image: mariadb:10.5
      command:
         - '--default-authentication-plugin=mysql_native_password'
         - '--character-set-server=utf8mb4'
         - '--collation-server=utf8mb4_unicode_ci'
         - '--skip-name-resolve'
      volumes:
         - ./db_volume:/var/lib/mysql
      cap_add:
         - SYS_NICE # CAP_SYS_NICE
      environment:
        MYSQL_INITDB_SKIP_TZINFO: '1'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
        ### Database initialization config:
        MARIADB_ROOT_PASSWORD: 'root123'
        MARIADB_USER: 'app'
        MARIADB_PASSWORD: 'app123'
        MARIADB_DATABASE: 'applights'
      ports:
         - 3380:3306
      restart: always
      # networks:
      #    - app_group

  wordpress:
      container_name: APP_wp_applights
      image: wordpress
      restart: always
      ports:
         - 8080:80
      environment:
         WORDPRESS_DB_HOST: mariadb
         WORDPRESS_DB_USER: 'app'
         WORDPRESS_DB_PASSWORD: 'app123'
         WORDPRESS_DB_NAME: 'applights'
      volumes:
         - ./wp_applights_volume:/var/www/html
         # - wp_applights_volume:/var/www/html
         - ./docker/config/php-custom.ini:/usr/local/etc/php/conf.d/custom.ini:cached,ro
      # networks:
      #    - app_group


# networks:
#    app_group:
#       external: false

# volumes:
#     wp_applights_volume:
#         driver: local
#     db_volume:
#         driver: local
```
