### DISCUSSION TITLE
data inside /var/www/html is getting override

### DISCUSSION THREAD

**Discussion by nishit93-hub** [docker-library/wordpress#724] [General]
Hi There,

I am creating my own docker image from image` WordPress`

```
FROM WordPress
COPY . /var/www/html
```
When I run the custom image on Kubernetes, whatever I copied data in the docker image gets overridden.
If logs it shows

```
WordPress not found in /var/www/html - copying now...
Complete! WordPress has been successfully copied to /var/www/html
```

**Comment by wglambert** [comment]
If `index.php` and `wp-includes/version.php` don't exist then "WordPress doesn't appear to be installed"

https://github.com/docker-library/wordpress/blob/1b7873367ec93d971105aa21a54185d889bbbee3/latest/php8.1/apache/docker-entrypoint.sh#L28-L37

**Comment by nishit93-hub** [comment]
@wglambert 
But I am copying  index.php and wp-includes/version.php to /var/www/html while creating docker image.
Actually, I am downloading the latest WordPress from wget `https://wordpress.org/latest.tar.gz `and copying everything inside that under the HTML directory.

**Comment by wglambert** [comment]
I can't reproduce, what's it look like in your directory with a `docker run --rm wordpress:test ls -l /var/www/html`? That'll skip the entrypoint and just see the files as-is

```console
$ ls
index.php    wp-activate.php     wp-comments-post.php  wp-cron.php        wp-load.php   wp-settings.php   xmlrpc.php
license.txt  wp-admin            wp-config-sample.php  wp-includes        wp-login.php  wp-signup.php
readme.html  wp-blog-header.php  wp-content            wp-links-opml.php  wp-mail.php   wp-trackback.php

$ docker build . -t wordpress:test
Sending build context to Docker daemon   61.1MB
Step 1/2 : FROM wordpress
 ---> d4f1eb34e2f5
Step 2/2 : COPY . /var/www/html
 ---> 55b494682859
Successfully built 55b494682859
Successfully tagged wordpress:test

$ kubectl run --image=wordpress:test wordpress
pod/wordpress created

$ kubectl logs wordpress
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.0.9. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.0.9. Set the 'ServerName' directive globally to suppress this message
[Mon Feb 14 17:00:00.916325 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.51 (Debian) PHP/7.4.27 configured -- resuming normal operations
[Mon Feb 14 17:00:00.916858 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

$ kubectl exec -it wordpress -- bash
root@wordpress:/var/www/html# ls -l
total 216
-rw-r--r--  1 root root    36 Feb 14 16:53 Dockerfile
-rw-r--r--  1 root root   405 Feb  6  2020 index.php
-rw-r--r--  1 root root 19915 Jan  1 00:15 license.txt
-rw-r--r--  1 root root  7437 Dec 28 17:38 readme.html
-rw-r--r--  1 root root  7165 Jan 21  2021 wp-activate.php
drwxr-xr-x  9 root root  4096 Feb 14 16:59 wp-admin
-rw-r--r--  1 root root   351 Feb  6  2020 wp-blog-header.php
-rw-r--r--  1 root root  2338 Nov  9 23:07 wp-comments-post.php
-rw-r--r--  1 root root  3001 Dec 14 08:44 wp-config-sample.php
drwxr-xr-x  5 root root  4096 Feb 14 16:59 wp-content
-rw-r--r--  1 root root  3939 Aug  3  2021 wp-cron.php
drwxr-xr-x 26 root root 12288 Feb 14 17:00 wp-includes
-rw-r--r--  1 root root  2496 Feb  6  2020 wp-links-opml.php
-rw-r--r--  1 root root  3900 May 15  2021 wp-load.php
-rw-r--r--  1 root root 47916 Jan  4 08:30 wp-login.php
-rw-r--r--  1 root root  8582 Sep 22 21:01 wp-mail.php
-rw-r--r--  1 root root 23025 Nov 30 17:32 wp-settings.php
-rw-r--r--  1 root root 31959 Oct 25 00:23 wp-signup.php
-rw-r--r--  1 root root  4747 Oct  8  2020 wp-trackback.php
-rw-r--r--  1 root root  3236 Jun  8  2020 xmlrpc.php
```

**Comment by nishit93-hub** [comment]
@wglambert 

Yes if I run my custom docker image from docker then it works fine, there it doesn't install WordPress. However, if run the same image on Kubernetes then it installs the WordPress there.

**Comment by nishit93-hub** [comment]
This is my manifest file

```
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
    type: frontend
spec:
  selector:
    app: wordpress
    type: frontend
  ports:
  - name: http-sv-port 
    port: 80
    targetPort: http-port
  - name: https-sv-port
    port: 443
    targetPort: https-port
  type: NodePort 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: px-file-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
    type: frontend
spec:
  selector:
    matchLabels:
      app: wordpress
      type: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        type: frontend
    spec:
      containers:
        - name: wordpress
          image: xxxxxxxxxxxxxxxxxx
          ports:
            - containerPort: 80
              name: http-port
            - containerPort: 443
              name: https-port
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-service
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbuser
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbpassword
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbname
          volumeMounts:
            - name: wordpress-vol
              mountPath: /var/www/html
      volumes:
        - name: wordpress-vol
          persistentVolumeClaim:
            claimName: wp-pv-claim

```

```
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: wordpress
    type: database
spec:
  selector:
    app: wordpress
    type: database
  ports:
  - port: 3306
    targetPort: db-port
  type: ClusterIP 
---
apiVersion: v1
data:
  dbname: d29yZHByZXNz
  dbpassword: cGFzc3dvcmQxMjM0
  dbrootpassword: cm9vdDEyMzQ=
  dbuser: dXNlcl93b3JkcHJlc3M=
kind: Secret
metadata:
  creationTimestamp: null
  name: mariadb-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: px-db-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: wordpress
    type: database
spec:
  selector:
    matchLabels:
      app: wordpress
      type: database
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        type: database
    spec:
      containers:
        - name: wordpress
          image: bitnami/mariadb:latest
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"         
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbuser
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbname
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbpassword 
          volumeMounts:
            - name: mariadb-vol
              mountPath: /bitnami/mariadb
      volumes:
        - name: mariadb-vol
          persistentVolumeClaim:
            claimName: mysql-pv-claim     
```

**Comment by nishit93-hub** [comment]
If I use the image in above manifest and deploy the WordPress then it install wordpress again there

**Comment by wglambert** [comment]
Your `mountPath` is overwriting that directory. I can't find where it says that in the k8s docs but yeah, it does that
```yaml
volumeMounts:
            - name: wordpress-vol
              mountPath: /var/www/html
```
And any reason for downloading https://wordpress.org/latest.tar.gz and hardcoding it in a Dockerfile when the Dockerfile already has it in `/usr/src/wordpress` (which is what's getting copied to `/var/www/html` if an existing install isn't detected)

https://github.com/docker-library/wordpress/blob/1b7873367ec93d971105aa21a54185d889bbbee3/latest/php8.1/apache/Dockerfile#L124-L131

Also `storage: 1Gi` seems kind of small
