### DISCUSSION TITLE
No first run setup page

### DISCUSSION THREAD

**Discussion by moorsey** [docker-library/wordpress#726] [General]
Just setup a new docker for wordpress, forwarded through nginx.

Wordpress default page loads fine, "my first site" etc, but from everywhere I have looked, I should get a first run page to set some details?

If I navigate to /wp-admin, I am asked for a username and password, but haven't set these.  Is there a default I should be trying?

docker-compose below:

```
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db_1
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: secret_pass
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - /path/wordpress:/var/www/html
    networks:
      - wordpress
      - proxy

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /path//db:/var/lib/mysql
    networks:
      - wordpress

networks:
  wordpress:
  proxy:
   external: true
```
