### DISCUSSION TITLE
Problems with updates and theme installations on version 6.0.2

### DISCUSSION THREAD

**Discussion by fedegibut** [docker-library/wordpress#744] [General]
I opened this thread to talk to the author of the Wordpress image.

I use this docker compose setup:

```
  wordpress:
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=...
      - WORDPRESS_DB_USER=...
      - WORDPRESS_DB_PASSWORD=...
      - WORDPRESS_DB_NAME=...
    volumes:
      - ./wordpress:/var/www/html/
```

I have two problems:

1) Docker files are not accessible after starting the project in Compose;
2) Wordpress asks me for the FTP parameters that I don't have when I'm locally. It is necessary to resort to the Linux OS hosting Docker and physically edit a Wordpress php file to solve.

**How do you solve these 2 problems?**

**Comment by wglambert** [comment]
Ensure you have the proper permissions on your volume, see https://github.com/docker-library/wordpress/issues/369#issuecomment-458634218

**Comment by fedegibut** [comment]
Thanks for your help.

The code that shows you how to download the 'wordpress' image from https://hub.docker.com, access the container shell, view the permissions of the various CMS files but not how to solve the problem.

What should I add in my .yaml file or in my Dockerfile?

_My configuration:_

```
drwxr-xr-x  5 www-data www-data  4096 Aug 31 19:05 .
drwxr-xr-x  1 root     root      4096 Aug 23 13:01 ..
-rw-r--r--  1 www-data www-data   261 Aug 31 19:05 .htaccess
-rw-r--r--  1 www-data www-data   405 Feb  6  2020 index.php
-rw-r--r--  1 www-data www-data 19915 Jan  1  2022 license.txt
-rw-r--r--  1 www-data www-data  7401 Mar 22 21:11 readme.html
-rw-r--r--  1 www-data www-data  7165 Jan 21  2021 wp-activate.php
drwxr-xr-x  9 www-data www-data  4096 Aug 30 17:40 wp-admin
-rw-r--r--  1 www-data www-data   351 Feb  6  2020 wp-blog-header.php
-rw-r--r--  1 www-data www-data  2338 Nov  9  2021 wp-comments-post.php
-rw-rw-r--  1 www-data www-data  5480 Aug 31 19:04 wp-config-docker.php
-rw-r--r--  1 www-data www-data  3001 Dec 14  2021 wp-config-sample.php
drwxr-xr-x  5 www-data www-data  4096 Aug 30 17:40 wp-content
-rw-r--r--  1 www-data www-data  3943 Apr 28 09:49 wp-cron.php
drwxr-xr-x 26 www-data www-data 16384 Aug 30 17:40 wp-includes
-rw-r--r--  1 www-data www-data  2494 Mar 19 20:31 wp-links-opml.php
-rw-r--r--  1 www-data www-data  3973 Apr 12 01:47 wp-load.php
-rw-r--r--  1 www-data www-data 48498 Apr 29 14:36 wp-login.php
-rw-r--r--  1 www-data www-data  8577 Mar 22 16:25 wp-mail.php
-rw-r--r--  1 www-data www-data 23706 Apr 12 09:26 wp-settings.php
-rw-r--r--  1 www-data www-data 32051 Apr 11 11:42 wp-signup.php
-rw-r--r--  1 www-data www-data  4748 Apr 11 11:42 wp-trackback.php
-rw-r--r--  1 www-data www-data  3236 Jun  8  2020 xmlrpc.php
```

_Correct configuration:_

```
drwxrwxrwx  5 www-data www-data  4096 Jan 29 17:26 .
drwxr-xr-x  4 root     root      4096 Jan 22 21:56 ..
-rw-r--r--  1 www-data www-data   234 Jan 29 17:26 .htaccess
-rw-r--r--  1 www-data www-data   418 Sep 25  2013 index.php
-rw-r--r--  1 www-data www-data 19935 Jan  3 16:24 license.txt
-rw-r--r--  1 www-data www-data  7415 Mar 18  2018 readme.html
-rw-r--r--  1 www-data www-data  6878 Dec 13 01:30 wp-activate.php
drwxr-xr-x  9 www-data www-data  4096 Jan  9 18:32 wp-admin
-rw-r--r--  1 www-data www-data   364 Dec 19  2015 wp-blog-header.php
-rw-r--r--  1 www-data www-data  1889 May  2  2018 wp-comments-post.php
-rw-r--r--  1 www-data www-data  2853 Dec 16  2015 wp-config-sample.php
drwxr-xr-x  4 www-data www-data  4096 Jan  9 18:32 wp-content
-rw-r--r--  1 www-data www-data  3669 Aug 20  2017 wp-cron.php
drwxr-xr-x 19 www-data www-data 12288 Jan  9 18:32 wp-includes
-rw-r--r--  1 www-data www-data  2422 Nov 21  2016 wp-links-opml.php
-rw-r--r--  1 www-data www-data  3306 Aug 22  2017 wp-load.php
-rw-r--r--  1 www-data www-data 37296 Dec 13 00:28 wp-login.php
-rw-r--r--  1 www-data www-data  8048 Jan 11  2017 wp-mail.php
-rw-r--r--  1 www-data www-data 17421 Oct 23 07:04 wp-settings.php
-rw-r--r--  1 www-data www-data 30091 Apr 29  2018 wp-signup.php
-rw-r--r--  1 www-data www-data  4620 Oct 23  2017 wp-trackback.php
-rw-r--r--  1 www-data www-data  3065 Aug 31  2016 xmlrpc.php
```

I use the following command to generate all images and containers.

`docker compose up -d --build`

**Comment by fedegibut** [comment]
If I use this type of volume:

```
    volumes:
      - wordpress:/var/www/html
      ...

volumes:
  wordpress:
```

everything works perfectly but I can't access the contents of the CMS. For example, if I want to download a photo from Google Cloud that I entered a year ago, I can't do it.
If I use this type of volume instead:

```
    volumes:
      - ./volumes/data-wordpress:/var/www/html
```

I can access the contents _but the permissions are not persistent_. I give an example.
**1)** I install wordpress in the following way;

```
version: '3.8'

services:

  mysql:
    build: ./mysql
    image: mysql-eb:v.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:6.0.2
    restart: always
    ports:
      - 8001:80
    environment:
      WORDPRESS_DB_HOST: 
      WORDPRESS_DB_USER: 
      WORDPRESS_DB_PASSWORD: 
      WORDPRESS_DB_NAME: 
    volumes:
      - ./volumes/data-wordpress:/var/www/html

  phpmyadmin:
    image: phpmyadmin:5.2.0
    ports:
      - '9000:80'
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
```

**2)** Everything works perfectly and I can't edit wordpress files;
**3)** Restart the OS hosting Docker;
**4)** After the restart the permissions have changed in fact I can access the php files of the volume and edit them directly from the host system.
**5)** If I launch this command everything starts working again:

`sudo chown -R www-data:www-data /home/gi/Dropbox/DOCKER/Docker-Php-MySQL/volumes/data-wordpress`

As you can see the permissions are not persistent.
**Is this an image bug?**
