### DISCUSSION TITLE
Correct cofiguration behind nginx

### DISCUSSION THREAD

**Discussion by raikoug** [docker-library/wordpress#773] [General]
Hi,
I really hope this is not duplicate, I searched but nothing..
I'm trying this composer:

```
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 127.0.0.1:9999:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pwd
      WORDPRESS_DB_NAME: dbname
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/sitename/wp'
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/sitename/db'
```

and this nginx conf for the site:
```
server {
    server_name FQDN;
    location / {
        proxy_pass http://127.0.0.1:9999/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto: https;
        proxy_set_header X-Forwarded-Host: FQDN;
        proxy_set_header X-Forwarded-Prefix /;
    }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/FQDN/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/FQDN/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = FQDN) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    server_name FQDN;
    listen 80;
    return 404; # managed by Certbot

}

```

But I see in console a lot of connection refused because the link provided are `http://127.0.0.1` :
`http://127.0.0.1:9999/wp-includes/blocks/navigation/style.min.css?ver=6.1.1 `
And If try to use https of the site I get redirected to `https://127.0.0.1/`

Why is it trying to use 127.0.0.1? Am I missing something important in the configuration?
I read the [Reverse Proxy Section](https://wordpress.org/support/article/administration-over-ssl/#using-a-reverse-proxy) on the wordpress documentation but can't understand it properly.
Do I need to change something in my proxy headers and/or adding a function on the file specifed?
Thanks

Riccardo
