### DISCUSSION TITLE
Can't upload theme with docker compose file

### DISCUSSION THREAD

**Discussion by crapthings** [docker-library/wordpress#804] [General]
i can't upload theme file it tells me link expired

how can i increase upload limit?

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/1147704/222886759-7e3d27c4-8ae7-4899-8edc-83b0668d46b3.png">

```yml
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 18001:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: test
      WORDPRESS_DB_NAME: test
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: test
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
```

**Comment by crapthings** [comment]
ok found solution

```yml
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 18001:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: test
      WORDPRESS_DB_NAME: test
    volumes:
      - wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: test
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
```

```
file_uploads = On
memory_limit = 64M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 600
```
