### DISCUSSION TITLE
Empty WP_DEBUG fails in docker swarm

### DISCUSSION THREAD

**Discussion by srouden** [docker-library/wordpress#820] [General]
In wp-config-docker.php WP_DEBUG is defined with:

define( 'WP_DEBUG', !!getenv_docker('WORDPRESS_DEBUG', '') );

if WORDPRESS_DEBUG is not defined in docker-compose.yml WP_DEBUG is set to the empty default value.
This is not a problem when using docker compose but when using docker stack deploy the result is the rather unhelpful message "Error establishing a database connection".
Explicitly setting WORDPRESS_DEBUG=false in docker-compose.yml solves this and both methods work as expected.

My suggestion is to change the definition of WP_DEBUG to explicitly set the default to false instead of empty:

define( 'WP_DEBUG', !!getenv_docker('WORDPRESS_DEBUG', false) );

or something similar should work.

**Comment by tianon** [comment]
That's weird - the `!!` will always be a boolean, so it's not actually empty, but is literally `false`:
```console
$ docker run --rm php -r 'var_dump(!!"");'
bool(false)
```
vs:
```console
$ docker run --rm php -r 'var_dump(!!"false");'
bool(true)
```
(we don't actually support setting that variable to the string "false" - the valid values are empty or non-empty)

In other words, something weirder is going on here, and your database connection is somehow not working unless debug is enabled? :thinking:  Are you sure you didn't make any other changes between the non-working deploy and the working one?  Is it possible the database wasn't fully initialized yet?

**Comment by srouden** [comment]
As this first happened a few days ago and I got it working I have moved on and don't have the exact files I used anymore. I wrote a new minimal example to try to reproduce the error again but was not able to. Now everything works just as I expect both with compose and swarm on the same docker-compose file without defining WORDPRESS_DEBUG.

This is what I did the first time and what led me to WORDPRESS_DEBUG. I ended up trying with something very similar to the docker-compose file below.
First I ran 
`docker stack deploy -c docker-compose.yml wpcluster`
and even after waiting for 10 minutes wordpress claimed that the database couldn't be found.
I installed the mysql client in the wordpress container and verified that the database could in fact be logged in to and that the wordpress database was there.
After removing the stack and deleting the volumes I retried with the exact same docker-compose file but using
`docker compose up -d`
instead. This time everything worked and I was greeted with the wordpress setup.
To troubleshoot I set WORDPRESS_DEBUG to 1 and restarted the stack and everything worked with docker stack deploy.
I retried the procedure a few times with and without WORDPRESS_DEBUG and it behaved precisely the same each time.
One side note to this is that if I first ran docker compose, setup wordpress and restarted with docker stack deploy while making sure that they used the same volumes the wordpress site was working, but a fresh start did not.

After my tests today I have no idea what happened but at least I'm confident that it has nothing to do with WORDPRESS_DEBUG.

You can close this case.

```
services: 
  mysql:
    image: mysql:debian
    volumes:
      - dbvol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_PASSWORD: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_DATABASE: "wordpress"

  wordpress: 
    image: wordpress:latest
    depends_on: 
      - mysql
    ports: 
      - 30000:80 
    volumes:
      - wpvol:/var/www/html 
    environment:
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress" 
      WORDPRESS_DB_HOST: "mysql:3306"
      WORDPRESS_DB_NAME: "wordpress"
      # WORDPRESS_DEBUG: false

volumes:
    dbvol:
    wpvol:
```
