### DISCUSSION TITLE
How to schedule restart apache ?

### DISCUSSION THREAD

**Discussion by jackchuong** [docker-library/wordpress#853] [General]
Hi all,
My docker-compose.yml
```
version: '3.1'
services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;'"
    networks:
      - wordpressnet
 
  wordpress-web:
    image: wordpress:6.2.2-php8.1-apache
    container_name: wordpress-web
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
      - ./apache2.conf:/etc/apache2/apache2.conf
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/opt/ssl/:ro
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./webdata:/var/www/html
      - ./ca-bundle.crt:/etc/ssl/certs/ca-certificates.crt:ro
    restart: always
    #command: "/bin/sh -c 'while :; do sleep 24h & wait $${!}; apache2ctl -t; done & apache2ctl -k graceful'"
    networks:
      - wordpressnet

  wordpress-mysql:
    #image: mysql:8.0.26
    image: mysql:5
    container_name: wordpress-mysql
    env_file:
      - .env
    #ports:
    #  - 3306:3306
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./mysqldata:/var/lib/mysql
    restart: always
    networks:
      - wordpressnet

networks:
  wordpressnet:
```
I edited docker-entrypoint.sh so wordpress apache support ssl
```
a2enmod ssl
#a2ensite default-ssl
service apache2 restart
service apache2 stop

exec "$@"
```
I want certbot container try to renew certificate every 24h and if certificate is renew, apache service in wordpress container should be restarted to load new certificate.
What is command to restart apache in wordpress-web container every 24h ?
I tried exec to wordpress-web container and run 
```
apache2ctl -k graceful
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.27.0.3. Set the 'ServerName' directive globally to suppress this message
httpd not running, trying to start
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
Action '-k graceful' failed.
The Apache error log may have more information.
```
