### DISCUSSION TITLE
Apache-Wordpress in kubernetes overwrites content of /var/www/html every container start

### DISCUSSION THREAD

**Discussion by ratermir** [docker-library/wordpress#854] [General]
I prepared Kubernetes deployment of the Wordpress image with Apache as a web server (latest version - 8.2) together with Mariadb and FTP server for external access to the files. 
I used persistent volume to keep content of "/var/www/html" (i. e. web content itself) persistent across restarts. 

Wordpress worked well, but the persistent wolume (originally mounted to "/var/www/html" and shared with the FTP server) was empty in the FTP container. Also if I changed or added anything in the "/var/www/html", it disapeared after POD restart. For example I installed Wordpress plugins via Wordpress GUI, they disapeared after restart (and also they disapeared from the filesystem)0

Do I anything wrong?

I also tried php-fpm-alpine variant of the image, where I mountef the volume also to the NGINX container. The persistent volume behaved as expected (it was visible from FTP, also survived the restart), but I had issues with coupling php-fpm and NGINX so I abandoned this path so far.

**Comment by LaurentGoderre** [comment]
Do you have a sample of the pod config?

**Comment by LaurentGoderre** [comment]
The following worked for me

```
apiVersion: v1
kind: Pod
metadata:
  name: wordpress-ftp
spec:
  containers:
  - name: wordpress
    image: wordpress:6-php8.2-apache
    env:
      - name: WORDPRESS_DB_HOST
        value: host.docker.internal:3306
      - name: WORDPRESS_DB_USER
        value: exampleuser
      - name: WORDPRESS_DB_PASSWORD
        value: examplepass
      - name: WORDPRESS_DB_NAME
        value: exampledb
    volumeMounts:
    - name: content
      mountPath: /var/www/html

  - name: ftp
    image: mikatux/ftps-server
    env:
      - name: USER
        value: wordpress
    volumeMounts:
    - name: content
      mountPath: /home/wordpress

  volumes:
  - name: content
    emptyDir: {}
```
