### DISCUSSION TITLE
Passing WP_ENVIRONMENT_TYPE not working

### DISCUSSION THREAD

**Discussion by ashishjullia** [docker-library/wordpress#871] [General]
I used the following `docker-compose.yml`:

```yaml
version: '3.8'

services:
  wordpress:
    image: wordpress:php8.1
    restart: always
    ports:
      - 8099:80
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: 1
      WP_ENVIRONMENT_TYPE: "development"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress-db
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"

  wordpress-db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  wordpress_data:
  db_data:
```

But still getting this:
![image](https://github.com/docker-library/wordpress/assets/11252951/ffa4db29-537f-468d-a2b0-47e8c8a0630d)

I looked here for the reference:
- https://github.com/docker-library/wordpress/issues/733
- https://developer.wordpress.org/apis/wp-config-php/#wp-environment-type

Also, I removed the volumes and then used new ones but the issue same issue. I even tried using `staging`, still same.

Am I missing something here?
