### DISCUSSION TITLE
Theme templates bug when port forwarding is different from host port 80

### DISCUSSION THREAD

**Discussion by git-davi** [docker-library/wordpress#888] [General]
Using docker compose yaml file:
```
services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
```
Seems to work fine.

But if the ports are mapped like `8080:80` (as suggested on the docker HUB guide) , or any other port eg `8000:80` etc.
The theme templates stop working. (I tested only on kadence and astra).
