### DISCUSSION TITLE
Docker Compose Wordpress Image wp-content directory looks like got merge instead of overwritten

### DISCUSSION THREAD

**Discussion by ramli-hartono** [docker-library/wordpress#910] [General]
My project directory looks like the following let's say the directory called `myawesomeproject` and is located at `~/src/myawesomeproject`, and inside that is the following
```
wp-content
 - mu-plugins
 - plugins
 - theme
   - newtheme
docker-compose.yml
```

and my `docker-compose.yml`
```
  # wordpress
  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
```

My question is when I run `docker compose up -d`
the `wp-content` directory seems like getting merged I can see my host machine become
```
wp-content
 - mu-plugins
 - plugins
 - theme
   - newtheme
   - twentytwentyfour
   - twentytwentythree
docker-compose.yml
```

Why is that? I was hoping the both the container and my host machine have my original project directory instead
```
wp-content
 - mu-plugins
 - plugins
 - theme
   - newtheme
docker-compose.yml
```

How can I fix this?
