### ISSUE TITLE
Login issues when scaling with docker-compose and tutum/haproxy

### ISSUE THREAD

**Issue by ahansson89** [docker-library/wordpress#112]
I have an issue when I try to setup this image and scale it behind an haproxy. I simply cannot log in to WordPress when I have more than one wordpress container running behind the proxy. This is my setup:
```
haproxy:
  image: tutum/haproxy
  ports:
    - 80:80
  links:
    - wordpress

wordpress:
  image: wordpress
  links:
    - db:mysql
  environment:
    WORDPRESS_DEBUG: 'true'

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: somepassword
  ports:
    - "3306:3306"
```
docker-compose scale wordpress=3
docker-compose up

Then I am trying to login to /wp-admin, but it is not logging me in. Not sure if it is a bug or me doing something wrong?
