### ISSUE TITLE
Can the charset also be defined as ENV?

### ISSUE THREAD

**Issue by csrui** [docker-library/wordpress#121]
I'm using it as the code below demonstrates but with no sucess

```
web:
    image: wordpress
    links:
        - mysql
    environment:
        - WORDPRESS_DB_CHARSET=latin1
        - WORDPRESS_DB_PASSWORD=password
        - WORDPRESS_DEBUG=true


Where can I find the available variables?

**Comment by tianon** [comment]
The variables this image responds to are the ones noted in the image description: https://github.com/docker-library/docs/blob/5ff8d735a7ac2128843bf10a46944884c4ce84c7/wordpress/README.md#how-to-use-this-image

If you're looking to change MySQL's default collation, I would recommend doing so on your MySQL container directly, as described in the MySQL image's description: https://github.com/docker-library/docs/blob/5ff8d735a7ac2128843bf10a46944884c4ce84c7/mysql/README.md#configuration-without-a-cnf-file

```yaml
version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: example
```
