### ISSUE TITLE
Using version 2 of docker-compose file descriptor, the database links is not found by the wordpress container

### ISSUE THREAD

**Issue by angelcervera** [docker-library/wordpress#134]
Error in the wordpress container:
```
wordpress_1 | error: missing WORDPRESS_DB_HOST and MYSQL_PORT_3306_TCP environment variables
wordpress_1 |   Did you forget to --link some_mysql_container:mysql or set an external db
wordpress_1 |   with -e WORDPRESS_DB_HOST=hostname:port?
```

Compose file:
```
version: '2'
services:
  wordpress:
    image: wordpress
    links:
      - db:mysql
    ports:
      - 8080:80
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: temporalpass
```

Environment:
```
~$ lsb_release -a; docker --version; docker-compose --version
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
Docker version 1.10.3, build 20f81dd
docker-compose version 1.6.2, build 4d72027
```

**Comment by ailic** [comment]
This comes with composer file, version 2. It's stated in [Docker documentation](https://docs.docker.com/compose/link-env-deprecated/).

> Note: Environment variables are no longer the recommended method for connecting to linked services. Instead, you should use the link name (by default, the name of the linked service) as the hostname to connect to. See the docker-compose.yml documentation for details.

What you have to do is to set the link name as the host name on which you wish to connect.

Your _wordpress_ section should look like this now:
```yaml
wordpress:
  image: wordpress
  environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_NAME: <db name>
    WORDPRESS_DB_PASSWORD: <db pass>
  ports:
    - 8080:80
```
