### ISSUE TITLE
Wait for mysql server to come up

### ISSUE THREAD

**Issue by dz0ny** [docker-library/wordpress#14]
```
mysql_1 | 141021 10:54:19  InnoDB: Waiting for the background threads to start
web_1   | PHP Warning:  mysqli::mysqli(): (HY000/2003): Can't connect to MySQL server on '172.17.0.27' (111) in - on line 5
web_1   | MySQL Connection Error: (2003) Can't connect to MySQL server on '172.17.0.27' (111)
```

```
web:
  image: wordpress
  ports:
   - 8000:80
  volumes:
   - ./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins/
  links:
   - mysql
mysql:
  image: orchardup/mysql
  ports:
    - 3306
  environment:
    MYSQL_DATABASE: wordpress
    MYSQL_ROOT_PASSWORD: wordpress


```
