### ISSUE TITLE
Multiple installations sharing databases/volumes

### ISSUE THREAD

**Issue by avidsapp** [docker-library/wordpress#141]
Spinning up multiple installations behind jwilder's nginx proxy as subdomains shares the same database/volume as the TLD. Clarification on how to separate databases/volumes and compose v2 advice would be much appreciated.

Docker-compose.yml:

```
db:
  image: mariadb:latest
  restart: always
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=****
    - MYSQL_DATABASE=****

dbdata:
  image: mariadb:latest
  entrypoint: /bin/echo
  command: data only container for db

web:
  build: .
  restart: always
  links:
    - db:mysql
  environment:
    - WORDPRESS_DB_PASSWORD=****
    - VIRTUAL_HOST=subdomain.tld.com
  working_dir: /var/www/html
  volumes:
    - wordpress/:/var/www/html/
    - ~/extends/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  ports:
    - "80"
    - "443"
```

**Comment by yosifkit** [comment]
If you are trying to just use `docker-compose scale` then I don't know of any way to do that.  You will have to duplicate each part. Something like this?

```yaml
# previous definitions here

db2:
  extends: db
  volumes-from: 
    - dbdata2
  environment:
    - MYSQL_ROOT_PASSWORD=new-password
    - MYSQL_DATABASE=other db
dbdata2:
  extends: dbdata
web2:
  extends: web
  links:
    - db2:mysql
```
If you don't mind them all using the same db server, you could use [`docker-entrypoint-initdb.d/`](https://github.com/docker-library/docs/tree/1b3709a5e8b4288f675667b05f77ea3788979f3d/mysql#initializing-a-fresh-instance) to create multiple databases, users, and passwords, but that might be putting too many concerns in one place.

The major differences in compose yaml v2 are here: https://docs.docker.com/compose/compose-file/#upgrading.

**Comment by avidsapp** [comment]
Thanks for your response. I'm not trying to scale. I'd like each subdomain.example.com to be a separate virtual host with separate container clusters, WP installs, databases, users, passwords, themes, plugins, etc from example.com so that they can be migrated elsewhere, added and killed without affecting example.com. This set-up works fine using the base WP image, but I noticed any clusters spun up using the Dockerfile/entrypoint for the WP install (to customize PHP extensions) either shares databases, volumes, or images with every other WP cluster using the same Dockerfile/entrypoint behind the same proxy. I assume this is written into the entrypoint, but don't know enough to dissect where.

**Comment by tianon** [comment]
Are you bind-mounting the same `wordpress/` directory into every site's container?  Each "install" of WordPress can only have a single `wp-config.php` file (which specifies the database it connects to), so if you want your subdomains to be completely isolated, then you must also ensure that both their databases (`/var/lib/mysql` in the MySQL container) and their runtime files (`/var/www/html` in the WordPress container) are completely separate.

**Comment by avidsapp** [comment]
@tianon - I believe this is the issue. Each site has its own `wordpress/` directory bind-mounted to the container. It was my understanding that the container bind-mounted this folder then installed WordPress and `wp-config.php` with env variables declaring the databases via docker-compose. It does not appear to act in this nature using the Dockerfile. Can you provide more details on differentiating between "installs"?

**Comment by tianon** [comment]
I think we're still not understanding how you're running this -- are you using a single `docker-compose.yml` which includes a separate service entry for each site, or a separate `docker-compose.yml` for each site?  Where are you storing the `wordpress/` directories on-disk?  Do you have more than one (if not, that's the cause of the problem you're running into)?

**Comment by avidsapp** [comment]
I'm using separate `docker-compose.yml` files for each site. There should be multiple `wordpress/` directories stored on disk in separate folders.

dir tree example:
- dev/
    - site 1/
        - Dockerfile
        - docker-entrypoint.sh
        - docker-compose.yml
        - wordpress/
            - index.php
            - wp-config.php
            - wp-content/
            - ...
   - site 2/
        - same as above
- prod/
    - site 1/
        - Dockerfile
        - docker-entrypoint.sh
        - docker-compose.yml
        - wordpress/
            - index.php
            - wp-config.php
            - wp-content/
            - ...
   - site 2/
        - same as above

**Comment by avidsapp** [comment]
A little more digging into the containers concluded that the `wp-config.php` for new sites is not being mounted correctly. I tried spinning up a new site with a fresh `wordpress/` download and customized `wp-config.php` with a new database. The new databases specified in `wp-config.php` are in `/var/lib/mysql` of the running MySQL container as well as other previously created databases (shouldn't be there), which are being incorrectly connected to by `wp-config.php` in `/var/www/html` in the WordPress container (wrong mounted `wp-config.php`). Using env vars injects the correct `wp-config.php` settings, but returns a 502 Bad Gateway.


example1.com docker-compose.yml:
```
db:
  image: mariadb:latest
  restart: always
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=mypass1
    - MYSQL_DATABASE=mydb1
  ports:
    - "3306"

dbdata:
  image: mariadb:latest
  entrypoint: /bin/echo
  command: data only container for db

web:
  build: .
  restart: always
  links:
    - db:mysql
  environment:
    - WORDPRESS_DB_HOST=db:mysql     #tried db:3306 and db
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_NAME=mydb1
    - WORDPRESS_DB_PASSWORD=mypass1
    - LETSENCRYPT_EMAIL=my@email
    - LETSENCRYPT_HOST=example1.com,www.example1.com
    - VIRTUAL_HOST=example1.com,www.example1.com
  working_dir: /var/www/html
  volumes:
    - wordpress/:/var/www/html/
    - ~/extends/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  ports:
    - "80"
    - "443"
```

example2.com (has separate WP installs as subdomains and purchased wildcard SSL) docker-compose.yml:
```
db:
  image: mariadb:latest
  restart: always
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=mypass2
    - MYSQL_DATABASE=mydb2

dbdata:
  image: mariadb:latest
  entrypoint: /bin/echo
  command: data only container for db

web:
  build: .
  restart: always
  links:
    - db:mysql
  environment:
    - WORDPRESS_DB_PASSWORD=mypass2
    - VIRTUAL_HOST=example2.com,www.example2.com
  working_dir: /var/www/html
  volumes:
    - wordpress/:/var/www/html/
    - ~/extends/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  ports:
    - "80"
    - "443"
```

sub1.example2.com docker-compose.yml:
```
db:
  image: mariadb:latest
  restart: always
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=mypass3
    - MYSQL_DATABASE=mydb3

dbdata:
  image: mariadb:latest
  entrypoint: /bin/echo
  command: data only container for db

web:
  build: .
  restart: always
  links:
    - db:mysql
  environment:
    - WORDPRESS_DB_PASSWORD=mypass3
    - VIRTUAL_HOST=sub1.example2.com
  working_dir: /var/www/html
  volumes:
    - wordpress/:/var/www/html/
    - ~/extends/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  ports:
    - "80"
    - "443"
```
