### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by martinvol** [docker-library/wordpress#164]
Hello, I did all the steps of the official [docker tutorial for Wordpress](https://docs.docker.com/compose/wordpress/) and it worked just fine in my local system.

But when I tried to deploy it on my server, doing exactly the same I got:

`$ curl localhost:8005
curl: (52) Empty reply from server
`

The only thing I changed is the forwarded port, resulting in this docker compose file:

```
version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    links:
      - db
    ports:
      - "8005:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
```

any clues?
