### ISSUE TITLE
Server configuration warning in WordPress at localhost:8888

### ISSUE THREAD

**Issue by andfinally** [docker-library/wordpress#189]
I'm on MacOS 10.12.1, with Docker 1.12.3 and with this composer file:

```
wordpress:
  container_name: wordpress
  image: wordpress:php7.0
  links:
    - wordpress_db:mysql
  ports:
    - 8888:80
  volumes:
    - "./wordpress:/var/www/html"
  environment:
    WORDPRESS_DB_PASSWORD: root
wordpress_db:
  container_name: mysql
  image: mariadb
  volumes:
    - "./data:/var/lib/mysql"
  environment:
    MYSQL_ROOT_PASSWORD: root
```

wp-admin is slow to load and I get 

> Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /var/www/html/wp-includes/update.php on line 123

From what I read, this is something to do with WP trying to use the wrong SSL library to update plugins.

**Comment by tianon** [comment]
I think we're going to need more information to reproduce this. :confused:

I took your `docker-compose.yml` as-is, only changing the external port from 8888 to 8081 for my own environment (have a conflict running on 8888 already), and tested it:

```console
$ docker-compose pull
Pulling wordpress_db (mariadb:latest)...
latest: Pulling from library/mariadb
Digest: sha256:6adb28c9adc0485698698b26d7080464d509602c2c5b125e1c5b331b14bc23fc
Status: Image is up to date for mariadb:latest
Pulling wordpress (wordpress:php7.0)...
php7.0: Pulling from library/wordpress
Digest: sha256:47ce44aa68a7b539108d48a2f9087bd12e91074b77285ed3dbfc8c3bac636d13
Status: Image is up to date for wordpress:php7.0
$ docker-compose up -d
Starting mysql
Starting wordpress
$ docker-compose logs -f
... # wait for everything to come up -- no errors displayed
```
Then I hit it in my browser and the setup process shows up as expected and everything appears to be working fine.

**Comment by andfinally** [comment]
Hm, I've tried switching to 8081, but I still get the issue. I get this on two different hosts, my home and work Macs, both Sierra, running on two different networks. 

From what I read on [WP support](https://wordpress.org/support/topic/something-may-be-wrong-with-wordpressorg-or-servers-configuration/), this issue is related to the fact that in El Capitan Apple  downgraded OpenSSL in favour of their own proprietary security library. (WordPress apparently needs at least OpenSSL 1.0 to send out encrypted communications.) 

The solution proposed for this is to [recompile your PHP to support OpenSSL](https://www.farces.com/wikis/naked-server/php/php-openssl/). Interestingly, when I try `php -i | grep "SSL Version"` on my WordPress container, I get `SSL Version => OpenSSL/1.0.1t`, which is what WordPress needs. But on my host machine I get `SSL Version => SecureTransport`. I would've thought if the container SSL library was correct there should be no problem.

![docker-wp-plugins](https://cloud.githubusercontent.com/assets/1647564/21095533/d65d7618-c053-11e6-9da3-bb0a06636f5d.png)

![docker-wp-warning](https://cloud.githubusercontent.com/assets/1647564/21095539/ddb43ef6-c053-11e6-95ec-32fc53b544c3.png)

**Comment by andfinally** [comment]
A colleague of mine on the same kind of Mac and the same WordPress and MySQL containers is not seeing this issue. When he runs `php -i | grep "SSL Version"` he gets the same result as me on host and container. He reckons if the container's SSL Version is correct there should be no problem.

**Comment by andfinally** [comment]
When I try with this docker-compose.yml I don't get the issue.

```
version: '2'
services:

  wordpress:
    image: wordpress:php7.0
    container_name: wordpress-1
    links:
      - mysql
    ports:
      - "88:80"
    environment:
      - WORDPRESS_DB_PASSWORD=secret
    working_dir: /var/www/html
    volumes:
      - ".html:/var/www/html"

  mysql:
    image: mariadb
    container_name: mysql-1
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
```

This is very similar to my original, except that there's no volume for the DB, and the port for WP is different. I may try deleting my images and starting afresh with my original to see what happens.
