### ISSUE TITLE
Failed opening '../woocommerce_slide/vendor/autoload.php'

### ISSUE THREAD

**Issue by MOHAMEDSEO** [docker-library/wordpress#210]
Hi,
I have a docker file like that:
```yaml
### Sources directory ##############@
  volumes_source:
    image: tianon/true
    volumes:
        - ./woocommerce:/var/www/html/wp-content/plugins/woocommerce
        - ./woocommerce_slide:/var/www/html/wp-content/plugins/woocommerce_slide
        - ./rosa:/var/www/html/wp-content/themes/rosa
        - ./16cafe:/var/www/html/wp-content/themes/16cafe
```
All of this folder are in root project (woocommerce,woocommerce_slide,rosa,16cafe).
When I'im in to 16cafe function file I want to call an autoload file from woocommerce_slide like that:
`require  "../woocommerce_slide/vendor/autoload.php";` but it give me this error : `Warning: include(): Failed opening '../woocommerce_slide/vendor/autoload.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/themes/16cafe/functions.php on line 39`
