### ISSUE TITLE
wp-config.php is truncated

### ISSUE THREAD

**Issue by Tarocco** [docker-library/wordpress#211]
I am setting up containers using docker-compose and after setting up my containers, the last line of my wp-config.php ends with

```
/** Sets up WordPress 
```

when a healthy wp-config.php file (i.e. compared with wp-config-sample.php) usually ends with

```
/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');
```

I believe the issue is being caused by an error in [docker-entrypoint.sh](https://github.com/docker-library/wordpress/blob/master/docker-entrypoint.sh) when it configures wp-config.php.

My docker-compose.yml:

```yml
version: '2'

services:
    nginx:
        image: nginx:mainline-alpine
        volumes:
            - ./wordpress:/var/www/wordpress/html
            - ./nginx/nginx.conf:/etc/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - ./nginx/log:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        restart: unless-stopped
        links:
            - wordpress:wordpress
    wordpress:
        image: wordpress:php7.1-fpm-alpine
        volumes:
            - ./wordpress:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./php/log:/var/log/php
        links:
            - wp-db:mysql
        environment:
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
        depends_on:
            - wp-db
    wp-db:
        image: mariadb:10.0
        volumes:
            - ./mysql:/var/lib/mysql:rw
        expose:
            - "3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - MYSQL_DATABASE=wordpress
```
