### ISSUE TITLE
[URGENT NEED] [Please Help Needed A Lot] - Unable to route nginx to wordpress (fpm or apache) for /subdirectory config

### ISSUE THREAD

**Issue by anirbanroydas** [docker-library/wordpress#221]
I have been trying this more than 12 hours and still not able to figure the perfect nginx config to route to a /blog wordpress installation. Need this in real urgent basis, have to shift company's blog to new location. Please Help!

I am documenting whatever I have tried so far but still no luck. Please tell me a uniform solution. Have read many blogs, may stackoverflow answers but all are giving different solutions hence no way going forward.

```
# nginx.conf

upstream wordpress_backend {
    server localhost:8002;
}


server {
  listen 80;
  server_name localhost;
  root /usr/share/nginx/html;

  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;

  index index.php index.html index.htm;

  location / {
    #root /usr/share/nginx/html;
    try_files $uri $uri/ =404;

  }

  error_page 404 /404.html;

  error_page 500 502 503 504 /50x.html;

  location = /50x.html {
        root /usr/share/nginx/html;
  }


  location = /blog {
        return 302 /blog/;
  }


  location /blog/ {


     proxy_set_header X-Forwarded-Host $host;
     proxy_set_header X-Forwarded-Server $host;
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     proxy_set_header X-Forwarded-Proto $scheme;
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header Host $http_host;


     #rewrite ^/blog(.*) $1  break;
     #proxy_pass http://wordpress_backend/;
     proxy_pass http://wordpress:80/;
  }

   rewrite ^/wp-admin(.*) $scheme://$http_host/blog/wp-admin$1 permanent;
   rewrite ^/wp-content(.*) $scheme://$http_host/blog/wp-content$1 permanent;
   rewrite ^/wp-includes(.*) $scheme://$http_host/blog/wp-inlcudes$1 permanent;
   rewrite ^/wp-login(.*) $scheme://$http_host/blog/wp-login$1 permanent;

#  location /blog {
#       #root /var/www/html/blog;
#        #index index.php index.html index.htm;
#        #rewrite /wp-admin$ $scheme://$host$uri/ permanent;
#        #try_files $uri $uri/ @blog;
#       rewrite /blog(.*) $1  break;
#       try_files $uri $uri/ /index.php?$args;
#  }

  #location @blog {
  #      rewrite ^/blog/(.*) /$1;
  #}




  #rewrite /blog/wp-admin$ $scheme://$host$uri/ permanent;
  # rewrite /wp-content$ $scheme://$host$uri/blog/wp-content$ permanent;

#  location ~ [^/]\.php(/|$) {
#    fastcgi_split_path_info ^(.+?\.php)(/.*)$;
#    if (!-f $document_root$fastcgi_script_name) {
#      return 404;
#    }

#    include fastcgi_params;
#    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#    fastcgi_param PATH_INFO       $fastcgi_path_info;
#     fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;

#    fastcgi_pass   wordpress:9000;
#    fastcgi_index  index.php;
#  }


  # Deny all attempts to access hidden files such as .htaccess, .htpasswd, .DS_Store (Mac).
  # Keep logging the requests to parse later (or to pass to firewall utilities such as fail2ban)
  location ~ /\. {
    deny all;
  }


}
```

As you can see, I have tried a lot of things, I have tried with wordpress fpm and wordpress apache, for fmp I used the /\.php location block, for apache I have used proxy_pass, but none of them are giving me, there is either some malformed redirect, sometimes the port is going away, and sometimes the proxy_pass not able to send the correct request to the wordpress.

My docker-compose file
```
version: '3.1'

services:

  wordpress:
    image: wordpress:4.7.5-php7.1-apache # have also tried with wordpress:4.7.5-fpm
    networks:
      - wordpress-test
    volumes:
      - ./wordpress-data:/var/www/html
    #ports:
    #  - 5002:80
    environment:
      WORDPRESS_DB_PASSWORD: ithakawordpresspass
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    networks:
      - ithaka-test
    volumes:
      - ./wordpress-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ithakawordpresspass

  nginx:
    build: nginx
    image: aroyd/nginx:latest
    networks:
      - ithaka-test
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      #- ./wordpress-data:/var/www/html
    ports:
      - "5001:80"
    depends_on:
      - wordpress
    #environment:
    # - NGINX_HOST=myhost
    # - NGINX_PORT=80

networks:
  wordpress-test:
    external: true
```

My nginx Dockerfile:
```
FROM nginx:1.13.0

RUN mkdir -p /var/www/html
RUN chown -R root:root /var/www/html
```

My `wordpress-test` network
```
sudo docker network create --attachable --driver=bridge wordpress-test
```

So when I am just running `wordpress` without using nginx, just the `apache` version then I am able to connect to it directly. But `nginx` routing giving me all kinds of trouble. Also, when I am using it at `location /` then its working fine, but my requirement is for `location /blog` and this is not happening at any cost. 

Please tell me how to solve this, either for `fpm version` or for the `apache version`, later on I am planning to route the docker nginx which has an exposed port from a standalone nginx from a different host.

Need Help on this urgently. I have looked for many sources. Still looking. Tried many combinations but not being able to solve it.
