### ISSUE TITLE
docker-compose bind overwrites host files

### ISSUE THREAD

**Issue by milanchotai** [docker-library/wordpress#235]
I want to use my own `wp-content` folder, not the image's, but the `bind` in service's `Volumes` section appears to be causing files from image's `wp-content` folder to be copied (and overwrite!) the host's. My docker-compose.yml: 

```
version: '3.3'

services:
   db:
     container_name: db
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     container_name: wordpress
     depends_on:
       - db
     image: wordpress:4.8.1-php7.1-apache
     volumes:
       - type: bind
         source: ./wp-content
         target: /var/www/html/wp-content
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

volumes:
    db_data:

```
I'm just running `docker-compose up -d`. I've also observed files of the same name are overwritten if I create them (i.e.: index.php). I've tried `:nocopy`, but since this is a bind not volume, it throws errors:

```
Cannot create container for service wordpress: invalid bind mount spec
invalid volume specification
invalid mount config for type "bind": field VolumeOptions must not be specified
```

If a bind shouldn't by default copy files, why is this happening?
