### ISSUE TITLE
WordPress failed to login when I have more than 1 replica.

### ISSUE THREAD

**Issue by chenxsan** [docker-library/wordpress#241]
Hi, this is what I have in my `docker-compose.yml` file:

```yml
version: '3.3'
services:
  wordpress:
    image: wordpress
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
       condition: on-failure
    ports:
      - "7777:80"
    environment:
      WORDPRESS_DB_HOST: ***
      WORDPRESS_DB_USER: ***
      WORDPRESS_DB_PASSWORD: ***
      WORDPRESS_DB_NAME: ***
    networks:
      - webnet
    volumes:
      - /home/sam/Sites/example.org/wp-content:/var/www/html/wp-content
networks:
  webnet:
```
And whenever I tried to login wordpress, I got redirected to `http://example.org/wp-login.php?redirect_to=http%3A%2F%2Fexample.org%2Fwp-admin%2F&reauth=1`.

If I changed the `replicas` to `1`, everything would work.

Anyone got this problem before? Would love to here some suggest here :)

BTW, I have nginx installed as the proxy:

```nginx
server {
        listen 80;

        server_name example.org;


        location / {
                proxy_pass http://127.0.0.1:7777;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
}
```
