### ISSUE TITLE
Changing PHP version to use 7

### ISSUE THREAD

**Issue by AllyReid** [docker-library/wordpress#255]
Can anyone help me change my container to support php7?

My current docker-compose.yml configuration 

``` yml
version: "2"
services:
  db:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  wordpress:
    image: wordpress
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    links:
      - db:mysql
    environment:
      WORDPRESS_DB_PASSWORD: root
```
