### ISSUE TITLE
Error response from daemon: manifest for wordpress:alpine not found

### ISSUE THREAD

**Issue by cnasikas** [docker-library/wordpress#268]
I get this error when I run the following docker `yml` file with `docker-compose`. I get also the same error with `docker pull wordpress:alpine`

The error: `Error response from daemon: manifest for wordpress:alpine not found`

```
version: '3'                                                                                             
services:                                                                                                
    wpdb:                                                                                                
        image: mariadb                                                                                   
        ports:                                                                                           
            - "8081:3306"                                                                                
        environment:                                                                                     
            MYSQL_ROOT_PASSWORD: "root_pass"                              
            MYSQL_DATABASE: "db"                                                             
            MYSQL_USER: "db_user"                                                                 
            MYSQL_PASSWORD: "db_pass"                                   
    wp:                                                                                   
        image: wordpress:alpine                                                                              
        volumes:                                                                                         
            - ./:/var/www/html                                                                           
        ports:                                                                                           
            - "8080:80"                                                                                  
        links:                                                                                           
            - wpdb:mysql                                                                                 
        environment:                                                                                     
            WORDPRESS_DB_USER: "db_user"                                                          
            WORDPRESS_DB_PASSWORD: "db_pass" 
```
