### ISSUE TITLE
Random "Error establishing a database connection" error

### ISSUE THREAD

**Issue by pavelsr** [docker-library/wordpress#270]
Error appeared absolutely randomly.
After reloading blog page several times I got working page.

My docker-compose:

```yaml
version: '3.1'

services:

  wordpress:
    container_name: my_blog
    image: wordpress:4.9.1-php7.2-apache
    restart: always
    expose:
      - "80"
    environment:
      WORDPRESS_DB_PASSWORD: password
    # env_file with VIRTUAL_HOST, LETSENCRYPT_HOST, LETSENCRYPT_EMAIL
    env_file:
      - production.env  
    depends_on:
      - "mysql"
    volumes:
      - ./www:/var/www/html
    networks:
          - proxy-tier

  mysql:
    container_name: my_blog_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
          - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```
