### ISSUE TITLE
docker-compose.yml does not work

### ISSUE THREAD

**Issue by huaweichen** [docker-library/wordpress#280]
I just simply followed: https://hub.docker.com/r/_/wordpress/ 
section: "... via docker stack deploy or docker-compose"

```yml
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```
I've setup my docker-compose in ubuntu 16.04
version is: `docker-compose version 1.16.1, build 6d1ac21`

Then I run `docker-compose stack.yml up -d`. 
Then I can see two container lauched:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                  NAMES
10f931f9ff08        mysql:5.7           "docker-entrypoint.s…"   4 minutes ago       Up 4 minutes        3306/tcp               wordpress_mysql_1
2337f1df60d7        wordpress           "docker-entrypoint.s…"   4 minutes ago       Up 10 seconds       0.0.0.0:8081->80/tcp   wordpress_wordpress_1
```

But if I go to browser: 
localhost:8081
`This site can’t be reached` is displayed.

***sigh***
