### ISSUE TITLE
WORDPRESS_DEBUG docker environment variable is not respected.

### ISSUE THREAD

**Issue by jstewart** [docker-library/wordpress#287]
It doesn't matter what you set `WP_DEBUG` or `WORDPRESS_DEBUG` to, the `wp-config.php` file always has `define('WP_DEBUG', true);`

Here's my compose file:

```
version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8082:80
    env_file: .env
    depends_on:
      - mysql
    networks:
      - dbnet
    environment:
      - WORDPRESS_DB_USER=redacted
      - WORDPRESS_DB_PASSWORD=redacted
      - WORDPRESS_DB_NAME=redacted
      - WORDPRESS_DEBUG=0


  mysql:
    image: mysql:5.7
    restart: always
    env_file: .env
    networks:
      - dbnet
    volumes:
      - mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  mysql:

networks:
  dbnet:
```

Wordpress appears to be copied successfully in the entrypoint:

```
wordpress_1  | WordPress not found in /var/www/html - copying now...
wordpress_1  | Complete! WordPress has been successfully copied to /var/www/html
wordpress_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
wordpress_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
wordpress_1  | [Wed Mar 07 13:41:44.583034 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.3 configured -- resuming normal operations
wordpress_1  | [Wed Mar 07 13:41:44.583505 2018] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

When I get into the running container (`docker-compose exec worpress bash`): 
```
root@a4405805893f:/var/www/html# grep DEBUG wp-config.php
 * It is strongly recommended that plugin and theme developers use WP_DEBUG
define('WP_DEBUG', true);
root@a4405805893f:/var/www/html# echo $WORDPRESS_DEBUG
0
```
I would expect to see `define('WP_DEBUG', false);` but it's true even when setting the env vars `WORDPRESS_DEBUG` to 0 or false.
