### ISSUE TITLE
Error php_network_getaddresses: getaddrinfo failed with docker

### ISSUE THREAD

**Issue by gomezv9** [docker-library/wordpress#303]
I'm trying to run my wordpress site by docker but it shows me some errors. Firstable it showed me:

`The server requested authentication method unknown to the client [caching_sha2_password]`

but I downgrade the mysql 8 to 5.7, but now it shows me:

`MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known`

Any idea to solve that ?

This is the .yml file:

```
version: '2'

services:
  ## Wordpress Container
  wordpress:
    container_name: afp_wordpress
    image: wp:afp
    volumes:
      - ./x_wordpress:/var/www/html
    ports:
      - 9001:9000
    environment:
      WORDPRESS_DB_USER: xxxx
      WORDPRESS_DB_PASSWORD: xxxxx
      WORDPRESS_DB_NAME: xxxxx
      WORDPRESS_TABLE_PREFIX: wp

  ## MySql
  mysql:
    container_name: afp_mysql
    image: mysql:5.7.18
    ports:
      - 3373:3306
    volumes:
      - ./x_mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: xxxxx
      MYSQL_DATABASE: xxxxxx

## Nginx Container
  nginx:
    container_name: afp_nginx
    image: ng:afp
    environment:
      PHP_FPM_SOCK: wordpress:9000
      SERVER_NAME: wordpress.dev
    ports:
      - 8080:80
    volumes:
      - ./x_wordpress:/var/www/html
      - ./x_nginx/ssl:/etc/nginx/ssl

  ## Composer Container
  composer:
    container_name: afp_composer
    image: composer/composer:1.1
    restart: 'no'
    command: install
    volumes:
      - ./x_wordpress:/app

```
