### ISSUE TITLE
Unable to setup WordPress

### ISSUE THREAD

**Issue by nillim** [docker-library/wordpress#308]
I installed WordPress in a Docker file and upon launch and initial setup it will prompt me that either I am entering an incorrect username/password or connection to my database server is disconnected (localhost)

Does this file already have a username/password and/or database setup?

**Comment by wglambert** [comment]
The [docs](https://github.com/docker-library/docs/tree/master/wordpress#how-to-use-this-image) state that the image has default user/pass innately.

Heres an example `docker-compose.yml` with a volume mounted for data persistence
```yml
version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - wordpress2:/var/lib/mysql
     networks:
     - wordpress
     environment:
       MYSQL_ROOT_PASSWORD: password 
       MYSQL_DATABASE: wordpress
       MYSQL_USER: username 
       MYSQL_PASSWORD: password 

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     networks:
     - wordpress
     volumes:
     - wp-content:/var/www/html/wp-content
     ports:
       - 80:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: username 
       WORDPRESS_DB_PASSWORD: password 

volumes:
 wordpress2:
 wp-content:
networks:
 wordpress:
```
