### ISSUE TITLE
Wordpress latest does not works with mysql latest container

### ISSUE THREAD

**Issue by shubhamrajvanshi** [docker-library/wordpress#313]
Wordpress latest does not works with mysql latest container.
I get below error in wordpress container logs.

Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22

MySQL Connection Error: (2054) The server requested authentication method unknown to the client

MySQL Connection Error: (2054) The server requested authentication method unknown to the client

Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22

**Comment by wglambert** [comment]
MySQL 8 changed the password authentication method. You're looking for the mysql_native_password plugin
https://dev.mysql.com/doc/refman/8.0/en/native-pluggable-authentication.html

So you'll want to connect with `mysql --default-auth=mysql_native_password -p`

Or you could use mysql 5.7

https://github.com/docker-library/mysql/issues/424#issuecomment-387403312

**Comment by shubhamrajvanshi** [comment]
Thanks @wglambert but how do I add this to my mysql image. I need to use public image and not self build one's

**Comment by yosifkit** [comment]
You just add it to the command (after the image on a docker run). Here is a docker compose:

```yaml
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
# or
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
# common options
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```
