### ISSUE TITLE
Not picking up password from linked mysql container

### ISSUE THREAD

**Issue by guidodobboletta** [docker-library/wordpress#339]
According to the documentation Docker Hub:

`-e WORDPRESS_DB_PASSWORD=... (defaults to the value of the MYSQL_ROOT_PASSWORD environment variable from the linked mysql container)`

I have this docker-compose file that should work but it doesn't. When trying to configure wordpress it still asks me for all my database information. 

After adding `WORDPRESS_DB_PASSWORD` to the wordpress service it actually works. 

It seems that the linked container code is not working at all, I've also had a look at the entrypoint script for the `wordpress:php7.0` image and couldn't find any reference to `MYSQL_ROOT_PASSWORD` neither on this entire github repo.
 
This is my compose file:

```
version: '3.7' 
services:     
  wordpress:   
   image: 'wordpress:php7.0' 
   ports: 
    - '5000:80'
   links:
     - mariadb:mysql

  mariadb:
   image: 'mariadb'
   ports:
    - '3306:3306'
   volumes: 
     - mariadb:/var/lib/mysql
   environment:
     - MYSQL_ROOT_PASSWORD=tmr

volumes:
  mariadb:
```
