### ISSUE TITLE
How should I add themes or plugins into the container?

### ISSUE THREAD

**Issue by ericandrewlewis** [docker-library/wordpress#341]
It's not obvious to me how I should add themes or plugins into the container. How should I do that?

I've tried making a volume in the `docker-compose.yml` like so:

```yml
version: '3.1'
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./some-theme:/var/www/html/wp-content/themes/some-theme
    environment:
      WORDPRESS_DB_PASSWORD: example
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```

but that does not work, I assume because of [a conflicting volume defined in the Dockerfile](https://github.com/docker-library/wordpress/blob/master/php7.2/fpm/Dockerfile#L42)

**Comment by wglambert** [comment]
https://github.com/docker-library/wordpress/issues/246#issuecomment-340557707
>If you'd like a fresh install from an image to include pre-installed themes or plugins, simply add them to the source directory in /usr/src/wordpress (which is what gets copied into /var/www/html at runtime).
`/var/www/html` is a volume because WordPress expects to be able to self-update.

**Comment by wglambert** [comment]
Also https://github.com/docker-library/wordpress/issues/146
Plugins go in `/usr/src/wordpress/wp-content/plugins`
Themes go in `/usr/src/wordpress/wp-content/themes`

And then copied over in the `docker-entrypoint.sh`
https://github.com/docker-library/wordpress/blob/f716ecef37ad5b3954363123aca109b762848b34/php7.2/fpm/docker-entrypoint.sh#L43-L55

**Comment by ericandrewlewis** [comment]
> If you'd like a fresh install from an image to include pre-installed themes or plugins, simply add them to the source directory in /usr/src/wordpress (which is what gets copied into /var/www/html at runtime).
/var/www/html is a volume because WordPress expects to be able to self-update.

I did this in a Dockerfile:

```
FROM wordpress

ADD ./some-theme /usr/src/wordpress/wp-content/themes/some-theme
```

Built it and ran it. I don't see the local folder in the container either under `/usr/src/wordpress/` or `/var/www/...`

Am I doing something wrong?

I would suggest we update the readme on Docker hub so it's clear how to do this after we have steps outlined.

**Comment by wglambert** [comment]
Using your Dockerfile it behaves as expected, perhaps you have some sort of permission error for the `ADD` to not work correctly.

docker-compose.yml
```yml
version: '3.1'

services:

  wordpress:
    image: wordpress:test
    restart: always
    ports:
      - 7070:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```
Dockerfile
```Dockerfile
FROM wordpress

ADD ./christmas-sweets /usr/src/wordpress/wp-content/themes/christmas-sweets
```

```console
$ docker build --no-cache . -t wordpress:test
Sending build context to Docker daemon      1MB
Step 1/2 : FROM wordpress
 ---> ca0fefec932b
Step 2/2 : ADD ./christmas-sweets /usr/src/wordpress/wp-content/themes/christmas-sweets
 ---> 94d8f5c26eaf
Successfully built 94d8f5c26eaf
Successfully tagged wordpress:test

$ docker exec -it 497 bash
root@497a72d283a0:/var/www/html# ls -l wp-content/themes/
total 20
drwxr-xr-x 7 www-data www-data 4096 Oct  9 17:42 christmas-sweets
-rw-r--r-- 1 www-data www-data   28 Jun  5  2014 index.php
drwxr-xr-x 6 www-data www-data 4096 Aug  2 20:39 twentyfifteen
drwxr-xr-x 5 www-data www-data 4096 Aug  2 20:39 twentyseventeen
drwxr-xr-x 7 www-data www-data 4096 Aug  2 20:39 twentysixteen
root@497a72d283a0:/var/www/html# ls -l wp-content/themes/christmas-sweets/
total 760
-rw-r--r-- 1 www-data www-data   1573 Oct  9 17:20 comments.php
-rw-r--r-- 1 www-data www-data   1878 Oct  9 17:20 content.php
drwxr-xr-x 2 www-data www-data   4096 Oct  9 17:20 css
-rw-r--r-- 1 www-data www-data   2604 Oct  9 17:20 footer.php
-rw-r--r-- 1 www-data www-data  12974 Oct  9 17:20 functions.php
-rw-r--r-- 1 www-data www-data   2026 Oct  9 17:20 header.php
drwxr-xr-x 2 www-data www-data   4096 Oct  9 17:20 images
drwxr-xr-x 2 www-data www-data   4096 Oct  9 17:20 inc
-rw-r--r-- 1 www-data www-data   3146 Oct  9 17:20 index.php
drwxr-xr-x 2 www-data www-data   4096 Oct  9 17:20 js
-rw-r--r-- 1 www-data www-data   5637 Oct  9 17:20 readme.txt
-rw-r--r-- 1 www-data www-data 647548 Oct  9 17:20 screenshot.png
-rw-r--r-- 1 www-data www-data    442 Oct  9 17:20 sidebar-shop.php
-rw-r--r-- 1 www-data www-data    436 Oct  9 17:20 sidebar.php
-rw-r--r-- 1 www-data www-data    872 Oct  9 17:20 singular.php
-rw-r--r-- 1 www-data www-data  47213 Oct  9 17:20 style.css
drwxr-xr-x 2 www-data www-data   4096 Oct  9 17:20 templates

root@497a72d283a0:/var/www/html# ls -l /usr/src/wordpress/wp-content/themes/christmas-sweets/
total 760
-rw-r--r-- 1 root root   1573 Oct  9 17:20 comments.php
-rw-r--r-- 1 root root   1878 Oct  9 17:20 content.php
drwxr-xr-x 2 root root   4096 Oct  9 17:20 css
-rw-r--r-- 1 root root   2604 Oct  9 17:20 footer.php
-rw-r--r-- 1 root root  12974 Oct  9 17:20 functions.php
-rw-r--r-- 1 root root   2026 Oct  9 17:20 header.php
drwxr-xr-x 2 root root   4096 Oct  9 17:20 images
drwxr-xr-x 2 root root   4096 Oct  9 17:20 inc
-rw-r--r-- 1 root root   3146 Oct  9 17:20 index.php
drwxr-xr-x 2 root root   4096 Oct  9 17:20 js
-rw-r--r-- 1 root root   5637 Oct  9 17:20 readme.txt
-rw-r--r-- 1 root root 647548 Oct  9 17:20 screenshot.png
-rw-r--r-- 1 root root    442 Oct  9 17:20 sidebar-shop.php
-rw-r--r-- 1 root root    436 Oct  9 17:20 sidebar.php
-rw-r--r-- 1 root root    872 Oct  9 17:20 singular.php
-rw-r--r-- 1 root root  47213 Oct  9 17:20 style.css
drwxr-xr-x 2 root root   4096 Oct  9 17:20 templates
```
