### ISSUE TITLE
Adding custom volume changes wp-content owner to root

### ISSUE THREAD

**Issue by antonlukin** [docker-library/wordpress#358]
I am using docker-compose to install WordPress.
When I add the volume with my custom developed theme, `wp-content` and `wp-content/themes` directories owner changes to root. So I can't upload images and update core.

Using docker just for developing I want to have ability to set my custom theme's owner to www-data, but I can't to set in on my host system, because I don't have such a system user.

```
version: '3'
services:
  database:
    image: mysql:5.7
    volumes:
        - database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
    networks:
      - back

  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    restart: always
    volumes:
      - wordpress:/var/www/html/wp-content:rw
      - ./app:/var/www/html/wp-content/themes/instapress:ro
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - 80:80
    networks:
      - back

volumes:
  database: {}
  wordpress: {}

networks:
  back:
```

Help me to understand how I can change dynamically my custom theme directory owner, please

<img width="259" alt="docker" src="https://user-images.githubusercontent.com/454185/50046626-2322a900-00b7-11e9-9f9a-ad7c93e2af9e.png">

**Comment by wglambert** [comment]
You're running Docker as the root user, I'm guessing Docker made your `wordpress` named volume owned by root somewhere along the way, however I'm not able to reproduce your issue even while running docker as root.  I'd recommend adding a non-superuser to the docker group and using that. Using a named volume shows the `/var/www/html/wp-content/` directory owned by `www-data` for me.
```yml
version: "3"

services:

 mysql:
    image: mysql:5.7
    volumes:
       - ./mysql/data:/var/lib/mysql
    environment:
       MYSQL_DATABASE: exampledb
       MYSQL_USER: exampleuser
       MYSQL_PASSWORD: examplepass
       MYSQL_RANDOM_ROOT_PASSWORD: '1'

 wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    volumes:
            - wp-content:/var/www/html/wp-content:rw
            - ./app:/var/www/html/wp-content/themes/instapress:ro
    environment:
       WORDPRESS_DB_HOST: mysql
       WORDPRESS_DB_USER: exampleuser
       WORDPRESS_DB_PASSWORD: examplepass
       WORDPRESS_DB_NAME: exampledb

volumes:
  wp-content:
```
```console
$ docker-compose up -d
Creating network "wordpress-358_default" with the default driver
Creating wordpress-358_wordpress_1 ... done
Creating wordpress-358_mysql_1     ... done
$ docker exec -it wordpress-358_wordpress_1 ls -l /var/www/html
total 196
-rw-r--r--  1 www-data www-data   418 Sep 25  2013 index.php
-rw-r--r--  1 www-data www-data 19935 Jan  6  2018 license.txt
-rw-r--r--  1 www-data www-data  7415 Mar 18  2018 readme.html
-rw-r--r--  1 www-data www-data  5458 May  1  2018 wp-activate.php
drwxr-xr-x  9 www-data www-data  4096 Aug  2 20:39 wp-admin
-rw-r--r--  1 www-data www-data   364 Dec 19  2015 wp-blog-header.php
-rw-r--r--  1 www-data www-data  1889 May  2  2018 wp-comments-post.php
-rw-r--r--  1 www-data www-data  2764 Dec 17 18:27 wp-config-sample.php
-rw-r--r--  1 www-data www-data  3156 Dec 17 18:27 wp-config.php
drwxr-xr-x  4 www-data www-data  4096 Aug  2 20:39 wp-content
-rw-r--r--  1 www-data www-data  3669 Aug 20  2017 wp-cron.php
drwxr-xr-x 18 www-data www-data 12288 Aug  2 20:39 wp-includes
-rw-r--r--  1 www-data www-data  2422 Nov 21  2016 wp-links-opml.php
-rw-r--r--  1 www-data www-data  3306 Aug 22  2017 wp-load.php
-rw-r--r--  1 www-data www-data 37794 Jul 16 14:14 wp-login.php
-rw-r--r--  1 www-data www-data  8048 Jan 11  2017 wp-mail.php
-rw-r--r--  1 www-data www-data 16246 Oct  4  2017 wp-settings.php
-rw-r--r--  1 www-data www-data 30091 Apr 29  2018 wp-signup.php
-rw-r--r--  1 www-data www-data  4620 Oct 23  2017 wp-trackback.php
-rw-r--r--  1 www-data www-data  3065 Aug 31  2016 xmlrpc.php
```
