### ISSUE TITLE
How to set a multisite workspace? Or change wp-config.php

### ISSUE THREAD

**Issue by JuicyLung91** [docker-library/wordpress#360]
When I define a volume for my theme then I cant mount the wp-config.php file. Is it possible to change the wp-config.php on docker-compose up command?

```version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: root
       MYSQL_PASSWORD: root

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: root
    volumes:
      - ./test-theme:/var/www/html/wp-content/themes/test-theme
      - ./test:/var/www/html/test
volumes:
    db_data: {}```

**Comment by wglambert** [comment]
The wp-config.php is auto-generated from your environment variables, so you can configure it further by using the [env vars](https://github.com/docker-library/docs/tree/master/wordpress#how-to-use-this-image) or not use any and mount your wp-config.php without it being generated.

**Comment by JuicyLung91** [comment]
Thanks. 

Am I doing something worng?

The wp-config is not having any of my  "WORDPRESS_CONFIG_EXTRA"

Already removed the container and reinstalled it with this docker.compose.yml file. 

 `web:
  image: wordpress
  volumes:
      - ./vpltorg:/var/www/html/wp-content/themes/vpltorg
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads
      - ./mitglieder:/var/www/html/mitglieder
  links:
  - mysql
  environment:
  - WORDPRESS_DB_PASSWORD=root
  ports:
  - "8080:80"
mysql:
  image: mysql:5.6
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DATABASE=vplt
  - WORDPRESS_CONFIG_EXTRA=
      define('WP_ALLOW_MULTISITE', true );
  ports:
  - 3306:3306`

**Comment by wglambert** [comment]
Using this docker-compose.yml it works
```yml
version: '3'
services:
   db:
     image: mysql:5.7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: root
       MYSQL_PASSWORD: root

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: root
       WORDPRESS_CONFIG_EXTRA: define('WP_ALLOW_MULTISITE', true );
```
```console
$ docker exec -it wordpress-360_wordpress_1 bash

root@c05456cc0af8:/var/www/html# grep -i multisite wp-config.php 
define('WP_ALLOW_MULTISITE', true );
```
