### ISSUE TITLE
Impossible file edit/permission in Linux

### ISSUE THREAD

**Issue by ecotechie** [docker-library/wordpress#367]
docker --version
Docker version 18.09.1, build 4c52b90

docker-compose --version
docker-compose version 1.23.2, build 1110ad01

Kubuntu(Ubuntu) Linux 18.10

docker-compose.yml
```
version: '3.7'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - ./app/wp-content:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  db:
    image: mariadb:latest
    volumes:
      - ./app/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db:

```

I create a new folder and the app subfolder. After running ```docker-compose up -d``` the wp-content folder structure is created.

I can rename the wp-content/plugins folder but can't rename the wp-content/plugins/akismet folder. They were both created automatically and have the same permissions and owner. www-data being user id 33 of which I'm a group member.

drwxr-xr-x 3 www-data www-data 4096 Jan  9 10:32 plugins
drwxr-xr-x 4 www-data www-data 4096 Jan  9 10:33 akismet

Seems like a bug?
