### ISSUE TITLE
How to support changing the upload file size limit

### ISSUE THREAD

**Issue by adriatic** [docker-library/wordpress#375]
I am proposing to expose the `/usr/local/etc/php` directory one can do a bind mount and specify overrides.

This proposal comes as a summary of the discussion at  https://forums.docker.com/t/how-to-get-access-to-php-ini-file/68986?u=monterey, trying to define the simplest method for solving the error condition `The uploaded file exceeds the upload_max_filesize directive in php.ini`

**Comment by gforghetti** [comment]
This also will also users to specify a custom `php.ini` file at container run time.

**Comment by wglambert** [comment]
Traditionally users would mount a `custom.ini` in the [$PHP_INI_DIR/conf.d/](https://github.com/docker-library/docs/tree/master/php#configuration), it looks like the WordPress documentation doesn't direct users to the php docs for information on configuring the image.

There was also this previous discussion on changing the upload file size limit https://github.com/docker-library/wordpress/issues/10#issuecomment-66906071

**Comment by wglambert** [comment]
`docker-compose.yml`
```yml
version: '3.6'

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: 123
```
Checking the changes
```console
$ docker-compose up -d
Creating network "wordpress-375_default" with the default driver
Creating wordpress ... done
Creating mysql     ... done

$ docker exec wordpress php -i | grep upload
/usr/local/etc/php/conf.d/uploads.ini
file_uploads => On => On
max_file_uploads => 20 => 20
upload_max_filesize => 256M => 256M
. . .
```
