### ISSUE TITLE
Weird containers mapping with userns-remap

### ISSUE THREAD

**Issue by lethyb** [docker-library/wordpress#377]
Hi everyone,

I'm currently facing a weird case scenario. I hope someone has already faced this and could help.

- On debian stretch : `Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`
- `1000:1000` is my uid:gid
- `Docker version 18.09.1, build 4c52b90`
- I'm using docker-compose : `docker-compose version 1.23.2, build 1110ad01`

- I'm pulling two images : `wordpress:php7.2-apache` & `mysql:5.5`

When starting the containers, everything works fine, files under the project root are owned by `www-data:www-data` (which is `33:33` on debian). Hence, these files are not writable, except trough sudo commands.

I decided to isolate containers with user namespace for mapping user permissions between containers and host, following the documentation https://docs.docker.com/engine/security/userns-remap/

Here is the content of my `/etc/docker/daemon.json` : 
```
{
	"userns-remap": "1000:1000"
}
``` 
`/etc/subuid` and `/etc/subgid` content : 
```
me:1000:65536
```

Then I perform a `daemon-reload` and restart docker.

Now, when I'm pulling again these two images, these files are now owned by the user `1033:1033`.
This user and this group do not even exist.

So, I tried a lot of things and I didn't find a valuable solution.
And then, I changed the mapping range under the `/etc/subuid` and `/etc/subgid` files. I found by substracting my uid and gid number by the `www-data` uid and gid I could get the correct rights for my project.

`/etc/subuid` and `/etc/subgid` content : 
```
me:967:65536
```

After reloading  the systemd manager configuration and restarting docker, these files under my project folder are well owned by me (1000:1000). Docker containers are running correctly and wordpress website accessible.

So... It's a trick. I don't know what is going on under the hood at this point and it seems really strange. I need to work in the meantime on that project, but I want to know if I've been right thus far or if I missed something, or if I'm wrong somehow.

In addition, here the output of my `docker-compose.yml` file
```
networks:
  default:
    driver: bridge
services:
  mysql:
    container_name: mysql
    environment:
      MYSQL_DATABASE: my_database_name
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: my_mysql_user_name
    expose:
    - '3306'
    image: mysql:5.5
    networks:
      default: null
    volumes:
    - /home/me/my_project/mysql:/var/lib/mysql:rw
  wordpress:
    container_name: wordpress
    depends_on:
    - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: my_database_name
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_USER: my_mysql_user_name
    image: wordpress:php7.2-apache
    networks:
      default: null
    ports:
    - 127.0.0.1:8080:80/tcp
    volumes:
    - /home/me/my_project:/var/www/html:rw
version: '3.3'
```

Any ideas ?

Thank you
