### ISSUE TITLE
Problem sending API requests between Docker containers

### ISSUE THREAD

**Issue by josherickson** [docker-library/wordpress#381]
Hi all, wondering if anyone can advise on a solution to this.

I have two Docker containers running on the same Docker network – wordpress and a python application. When I send a request from the python application to the wordpress API, I receive a 302 (redirect) to `http://localhost/`. This is of course a problem because if I follow that redirect from within the python container, it is now making that request to itself.

Sample code within Python container
```
>>> import requests
>>> r = requests.get('http://wordpress/wp-json', allow_redirects=False)
>>> r.headers
{'Date': 'Fri, 22 Feb 2019 18:56:43 GMT', 'Server': 'Apache/2.4.25 (Debian)', 'X-Powered-By': 'PHP/7.2.14', 'Location': 'http://localhost/', 'Content-Length': '0', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Content-Type': 'text/html; charset=UTF-8'}
```

Sample docker-compose.yaml
```
version: "3.5"

networks:
  network:
    name: wp_network

services:
  python-app:
    image: python:3.7-alpine
    networks:
      - network
    ports:
      - "6529:80"
  wordpress:
    environment:
      - WORDPRESS_DB_HOST=mysql-wordpress
      - WORDPRESS_DB_USER=local
      - WORDPRESS_DB_PASSWORD=secret
      - WORDPRESS_DB_NAME=wordpress_local
    image: wordpress
    networks:
      - network
    ports:
      - "80:80"
  mysql-wordpress:
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=local
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=wordpress_local
    image: mysql:5.7
    networks:
      - network
    ports:
      - "3306:3306"
```

A couple (probably relevant) statements from `wp-config.php`
```
define("MULTISITE", true)
define("SUBDOMAIN_INSTALL", false)
define("DOMAIN_CURRENT_SITE", "localhost")
define("PATH_CURRENT_SITE", "/")
```

Is there a way that I can configure WordPress so that it (a) doesn't redirect and instead just returns the response directly, (b) redirects to the same host name that was provided as part of the request or (c) set up its hostname to be `wordpress` (the docker container name) without breaking it.

Regarding (c), if I change the line to `define("DOMAIN_CURRENT_SITE", "wordpress")`, then requests instead return a response containing `500: Error establishing a database connection`. Not to mention, that I can then no longer access it from my host machine anymore.
