### ISSUE TITLE
Docker Desktop breaks WordPress after restart

### ISSUE THREAD

**Issue by dmxd5** [docker-library/wordpress#395]
Once I restart Docker Desktop, my newly installed custom theme as well as newly installed plugins no longer work in my WordPress installation running on official WordPress docker image. If I restart only containers, not the Docker Desktop, no issues occur (until I restart Docker Desktop).

The following message appears in the admin panel in my WordPress after the Docker Desktop restart:

> The active theme is broken. Reverting to the default theme.

The same theme works perfectly fine on non-docker WordPress installations.

My ***docker-compose.yaml***:
```yml
version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
```
