### ISSUE TITLE
Installing plugin fails to create folder (vsftpd and Loco)

### ISSUE THREAD

**Issue by flaviops** [docker-library/wordpress#397]
Hi,

I'm having issues when installing the Loco plugin to my Wordpress.

The plugin requires a ftp server, so I installed vsftpd on my host machine using the following tutorial: [Link](https://www.techrepublic.com/article/how-to-quickly-setup-an-ftp-server-on-ubuntu-18-04/)

The configuration file is the same as the tutorial (/etc/vsftpd.conf):
```
listen=NO
listen_ipv6=YES
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
chroot_local_user=YES
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
rsa_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
rsa_private_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
ssl_enable=NO
pasv_enable=Yes
pasv_min_port=10000
pasv_max_port=10100
allow_writeable_chroot=YES
```

When I click the "Install Now" button, insert the IP, user and password for ftpuser it shows the following error:
![image](https://user-images.githubusercontent.com/1262784/56499842-9e212380-64de-11e9-949f-6e7d0ef6466e.png)

Upon inspecting the vsftpd log (/var/log/vsftpd.log) I saw this error:
```
[ftpuser] FAIL MKDIR: Client "::ffff:172.23.0.3", "/docker_volumes/wordpress-container/html/wp-content/plugins/loco-translate"
```

Some lines prior it seems that the ftpuser have permission to write on some directories:
```
[ftpuser] OK MKDIR: Client "::ffff:172.23.0.3", "/docker_volumes/wordpress-container/html/wp-content/upgrade/loco-translate.2.2.2-uCh8VE/loco-translate/tpl/debug"
```

I have tried to change the directory permissions, which resulted in the same error:
```
drwxrwxrwx 16 www-data www-data 4.0K Apr 22 11:54  plugins
drwxrwxrwx  2 www-data www-data 4.0K Apr 12 16:22  upgrade
```

Am I missing some configuration or I'm using the ftp wrongly?

Thanks.

**Comment by wglambert** [comment]
https://github.com/docker-library/wordpress/issues/298#issuecomment-428013226
>if you're getting prompted for FTP credentials, it's because of your filesystem permissions. I think you'll find that if you correct the filesystem permissions, the prompt will go away and installations will complete successfully automatically within the Web UI (since the www-data user that the PHP code runs as needs to be able to write to the directories in order for the web-based installation to succeed).

I was able to install it through the webui using this docker-compose file
```yml
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
```
![Spectacle Et1169](https://user-images.githubusercontent.com/26428991/56511476-87c89700-64e1-11e9-8535-e565e928cbe2.png)
