### ISSUE TITLE
PHP-FPM Default Listen Port is Localhost

### ISSUE THREAD

**Issue by JAP42** [docker-library/wordpress#406]
Using version 7.3 the default www.conf file listens only on 127.0.0.1. Makes it difficult to deploy as a separate container.

**Comment by tianon** [comment]
See `zz-docker.conf` where that value gets overridden:

https://github.com/docker-library/php/blob/fa29b56ad42282d58e10f5e449be45e8d905cfe6/7.3/stretch/fpm/Dockerfile#L257-L263

```dockerfile
	&& { \
		echo '[global]'; \
		echo 'daemonize = no'; \
		echo; \
		echo '[www]'; \
		echo 'listen = 9000'; \
	} | tee php-fpm.d/zz-docker.conf
```

**Comment by JAP42** [comment]
Interesting, Using wordpress:php7.3-fpm it does not listen on 9000 from outside the container. I switched to the official PHP container and manually added the wordpress files and all works fine. I will take a deeper look, however I do not recall seeing a zz-docker.conf file in the php-fpm.d directory.

**Comment by JAP42** [comment]
Having to reinstall some containers and can not for the life of me remember how I made the image I was using because I did not push it to the repo and I have lost the docker file. 
I am hoping to solve the issue of this container not listening on port 9000

This is my docker compose, Pretty straight forward, PHP (Wordpress), Mysql, and nginx behind Traefik. 
```
version: '3.6'
services:

  wordpress:
    image: jap42/wordpress
    volumes:
      - "./www:/var/www"
#      - "./config/php:/usr/local/etc/php-fpm.d"
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${PASSWORD}
    depends_on:
      - mysql
    restart: always
    networks:
      - internal

  mysql:
    image: mariadb:latest
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=wordpress
    restart: always
    networks:
      - internal

  nginx:
    image: nginx:stable-alpine
    volumes:
      - "./config/nginx:/etc/nginx/conf.d"
      - "./logs/nginx:/var/log/nginx"
      - "./www/html:/var/www/html"
    depends_on:
      - wordpress
    labels:
      - "traefik.enable=TRUE"
      - "traefik.backend=${URL}"
      - "traefik.frontend.rule=Host:${URL}"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.port=80"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=0"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=false"
      - "traefik.frontend.headers.SSLHost=${URL}"
      - "traefik.frontend.headers.STSIncludeSubdomains=false"
      - "traefik.frontend.headers.STSPreload=false"
      - "traefik.frontend.headers.frameDeny=true"
    restart: always
    networks:
      - traefik_proxy
      - internal
    command: [nginx-debug, '-g', 'daemon off;']

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  internal:
    driver: bridge
```
Using the wordpress image this is what I get in nginx: `[error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.2, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "example.com", referrer: "https://example.com"`

The ip is correct, resolved by the docker hostname. 

This exact config with the PHP-FPM image works fine. zz-docker.conf exists and includes `listen = 9000` I tried changing it to `0.0.0.0:9000` with no luck.
