### ISSUE TITLE
No write permission and no other selectable languages

### ISSUE THREAD

**Issue by cmp102** [docker-library/wordpress#426]
Hi, I'm using this docker-compose.yml file
```
version: '3'
services:
        wordpress:
                image: wordpress
                restart: always
                ports:
                        - 80:80
                volumes:
                        - ./themes:/var/www/html/wp-content/themes/
                        - ./plugins:/var/www/html/wp-content/plugins/
                environment:
                        WORDPRESS_DB_HOST: mariadb
                        WORDPRESS_DB_USER: testuser
                        WORDPRESS_DB_PASSWORD: testpassword
                        WORDPRESS_DB_NAME: testdb
        mariadb:
                image: mariadb:10.1
                environment:
                        TZ: Europe/Madrid
                        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
                        MYSQL_ROOT_PASSWORD: rootpwd
                        MYSQL_USER: testuser
                        MYSQL_PASSWORD: testpassword
                        MYSQL_DATABASE: testdb
```
But I can't update wordpress or install themes / plugins from the web interface.
I also cannot change to a language other than English.
Can these things not be done with this kind of images or am I doing something wrong?
