### ISSUE TITLE
Rewrite rule applied to static files

### ISSUE THREAD

**Issue by ThibaultVlacich** [docker-library/wordpress#433]
Hello,

I'm using this docker image and I have an issue. Static files are rewrited to the index.php.

Here's a link to my Wordpress website I'm hosting using this image: https://thibault.vlacich.fr/blog/

Here's an example of a file: https://thibault.vlacich.fr/blog/wp-includes/js/wp-embed.min.js?ver=5.2.3

Here's my Docker Compose config file:
```yaml
version: '3.7'

networks:
  http_network:
    external: true
  thibaultvlacich:
    external: false

services:
  database:
    image: mariadb:latest
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - thibaultvlacich

  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('FORCE_SSL_ADMIN', false);
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:thibault.vlacich.fr;PathPrefix:/blog
      - traefik.port=80
      - traefik.docker.network=http_network
    networks:
      - thibaultvlacich
      - http_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    links:
      - database
    networks:
      - http_network
      - thibaultvlacich
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:phpmyadmin.vlacich.fr
      - traefik.port=80
      - traefik.docker.network=http_network
```

As you can see I'm using Traefik also, but I doubt it's the issue.
