### ISSUE TITLE
Delete all file under every folders

### ISSUE THREAD

**Issue by Boxjan** [docker-library/wordpress#448]
I use a docker-compose, and here is my docker-compose.yml
``` 
version: "3"

services:
  backend:
    image: wordpress:latest
    ports: 
      - "127.0.0.1:8081:80"
    volumes:
      - wp_data:/var/www/html
    extra_hosts:
      - "db:172.18.0.1"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: blog
      WORDPRESS_DB_PASSWORD: blog
      WORDPRESS_DB_NAME: blog

volumes:
  wp_data: 
    driver: local
    driver_opts:
      type: none
      device: /home/docker/blog/wp
      o: bind
```
I usually modify the files in docker by modifying the files on the system.(Include Cut Delete Copy, and I will use ``` chown -R www-data:www-data /home/docker/blog/wp ``` to give )
Sometime I will found every folders have no file but the folders is still here.
It will happen once or two every month. Even I not modify any file.

I have no idea about it, even I just restart nginx or system, it can happen too.
