### ISSUE TITLE
wp-content folder is being created as root and is empty

### ISSUE THREAD

**Issue by Darksoulsong** [docker-library/wordpress#449]
`wp-content` dir is empty, and being created as `root` and not `www-data` like everything else. 

I'm running docker desktop 2.1.0.4  on a macos. My config is below:
```
version: '3.1'
networks:
  default:
    external:
      name: webproxy
services:
  db-site1:
    container_name: db-site1
    environment:
      MYSQL_DATABASE: db-site1
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: user
    image: mariadb:latest
    restart: unless-stopped
    volumes:
    - /Users/user/Documents/sandbox.nosync/www/site1/data/db:/var/lib/mysql:rw
  
  site1:
    container_name: site1
    depends_on:
    - db-site1
    environment:
      LETSENCRYPT_EMAIL: mail@gmail.com
      LETSENCRYPT_HOST: site1.local,www.site1.local
      VIRTUAL_HOST: site1.local,www.site1.local
      WORDPRESS_DB_HOST: db-site1:3306
      WORDPRESS_DB_NAME: db-site1
      WORDPRESS_DB_PASSWORD: pwd
      WORDPRESS_DB_USER: user
      WORDPRESS_TABLE_PREFIX: wp_site1
    image: wordpress:latest
    logging:
      options:
        max-size: 200k
    restart: unless-stopped
    volumes:
    - /Users/user/Documents/sandbox.nosync/www/site1/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:rw
    - /Users/user/Documents/sandbox.nosync/www/site1/conf.d/uploadsize.conf:/usr/local/etc/php/conf.d/uploadsize.conf:rw
    - /Users/user/Documents/sandbox.nosync/www/data/site/wordpress-core:/var/www/html:rw
    - /Users/user/Documents/sandbox.nosync/www/site1/data/wp-content:/var/www/html/wp-content:rw

```

And these are the folders created on the container. 
```
-rw-r--r--   1 root     root     274176 Oct 21 17:39 'C:\xampp\php\logs\php_error_log'
-rw-r--r--   1 www-data www-data    420 Nov 30  2017  index.php
-rw-r--r--   1 www-data www-data  19935 Jan  1  2019  license.txt
-rw-r--r--   1 www-data www-data   7447 Apr  8  2019  readme.html
-rw-r--r--   1 www-data www-data   6919 Jan 12  2019  wp-activate.php
drwxr-xr-x  93 www-data www-data   2976 Sep  5 01:08  wp-admin
-rw-r--r--   1 www-data www-data    369 Nov 30  2017  wp-blog-header.php
-rw-r--r--   1 www-data www-data   2283 Jan 21  2019  wp-comments-post.php
-rw-r--r--   1 www-data www-data   2808 Oct 29 16:22  wp-config-sample.php
-rw-r--r--   1 www-data www-data   3191 Oct 29 16:22  wp-config.php
drwxr-xr-x   2 root     root         64 Oct 29 14:16  wp-content
-rw-r--r--   1 www-data www-data   3847 Jan  9  2019  wp-cron.php
drwxr-xr-x 204 www-data www-data   6528 Sep  5 01:08  wp-includes
-rw-r--r--   1 www-data www-data   2502 Jan 16  2019  wp-links-opml.php
-rw-r--r--   1 www-data www-data   3306 Nov 30  2017  wp-load.php
-rw-r--r--   1 www-data www-data  39551 Jun 10 13:34  wp-login.php
-rw-r--r--   1 www-data www-data   8403 Nov 30  2017  wp-mail.php
-rw-r--r--   1 www-data www-data  18962 Mar 28  2019  wp-settings.php
-rw-r--r--   1 www-data www-data  31085 Jan 16  2019  wp-signup.php
-rw-r--r--   1 www-data www-data   4764 Nov 30  2017  wp-trackback.php
-rw-r--r--   1 www-data www-data   3068 Aug 17  2018  xmlrpc.php
```
