### ISSUE TITLE
when changing domains, assets still use old domain urls

### ISSUE THREAD

**Issue by dave-dm** [docker-library/wordpress#450]
I made the wp site on my local mac using localhost. Then I git commited the entire thing and transferred to my hosting using http://ip:port instead of localhost. Then I edited wp-config `define('DOMAIN_CURRENT_SITE', 'localhost');` and mySQL tables `wp_blogs`, `wp_site`, `wp_sitemeta`.

Now all the assets still reference localhost instead of http://ip:port so I see the text but no css/js/images.

I'm guessing it's some apache setting problem?

This is my docker compose:

```yaml
version: '3.3'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./files:/var/www/html
      # basic http auth
      - ./apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/.htpasswd:/etc/apache2/.htpasswd

    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password

  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: username
      MYSQL_USER: username
      MYSQL_PASSWORD: password
```
