### ISSUE TITLE
wordpress:php7.4-fpm-alpine - MySQL Connection Error: (2002) Connection

### ISSUE THREAD

**Issue by asolopovas** [docker-library/wordpress#460]
Hi I am creating docker-compose file which will be using nginx reverse proxy via php-fpm, the problem that I get is that whenever wordpress-php7.4-fpm-alipe starts it throws:
```
wordpress_1  | WordPress not found in /var/www/html - copying now...
wordpress_1  | WARNING: /var/www/html is not empty! (copying anyhow)
wordpress_1  | Complete! WordPress has been successfully copied to /var/www/html
wordpress_1  | [03-Jan-2020 15:28:12 UTC] PHP Warning:  mysqli::__construct(): (HY000/2002): Connection refused in Standard input code on line 22
wordpress_1  |
wordpress_1  | MySQL Connection Error: (2002) Connection refused
wordpress_1  |
wordpress_1  | MySQL Connection Error: (2002) Connection refused
wordpress_1  |
wordpress_1  | MySQL Connection Error: (2002) Connection refused
wordpress_1  |
wordpress_1  | MySQL Connection Error: (2002) Connection refused
wordpress_1  |
wordpress_1  | MySQL Connection Error: (2002) Connection refused
wordpress_1  |
wordpress_1  | MySQL Connection Error: (2002) Connection refused
wordpress_1  |
wordpress_1  | MySQL Connection Error: (2002) Connection refused
wordpress_1  |
wordpress_1  | MySQL Connection Error: (2002) Connection refused
wordpress_1  |
wordpress_1  | MySQL Connection Error: (2002) Connection refused
wordpress_1  |
wordpress_1  | MySQL Connection Error: (2002) Connection refused
wordpress_1  |
wordpress_1  | WARNING: unable to establish a database connection to 'mariadb'
wordpress_1  |   continuing anyways (which might have unexpected results)
wordpress_1  |
wordpress_1  | [03-Jan-2020 15:28:39] NOTICE: fpm is running, pid 1
wordpress_1  | [03-Jan-2020 15:28:39] NOTICE: ready to handle connections

```
Here is my docker compose yml:
```docker
version: "3.2"
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: default_wp
      MYSQL_USER: default_wp
      MYSQL_PASSWORD: secret
    volumes:
     - db:/var/lib/mysql
  wordpress:
    image: wordpress:php7.4-fpm-alpine
    depends_on:
      - mariadb
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: default_wp
      WORDPRESS_DB_USER: default_wp
      WORDPRESS_DB_PASSWORD: secret
    volumes:
      - wp:/var/www/html
      - wp-uploads:/var/www/html/wp-content/uploads
      - wp-theme:/var/www/html/wp-content/themes/theme
      - vendor:/var/www/html/wp-content/themes/theme/vendor

volumes:
  db:
  wp:
  vendor:
  node_modules:
  wp-uploads:
    external: true
  wp-theme:
    external: true
```
Is there any particular reason behind that?

**Comment by asolopovas** [comment]
If I use docker-compose.yml from https://hub.docker.com/_/wordpress
```
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
```

 I get the following errors on initial start:
```
Creating volume "wordpresstest_wordpress" with default driver
Creating volume "wordpresstest_db" with default driver
Creating wordpresstest_wordpress_1 ... done
Attaching to wordpresstest_wordpress_1
wordpress_1  | WordPress not found in /var/www/html - copying now...
wordpress_1  | Complete! WordPress has been successfully copied to /var/www/html
wordpress_1  | [03-Jan-2020 16:00:21 UTC] PHP Warning:  mysqli::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in Standard input code on line 22
wordpress_1  | [03-Jan-2020 16:00:21 UTC] PHP Warning:  mysqli::__construct(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in Standard input code on line 22
wordpress_1  |
wordpress_1  | MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known
wordpress_1  | [03-Jan-2020 16:00:24 UTC] PHP Warning:  mysqli::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in Standard input code on line 22
wordpress_1  | [03-Jan-2020 16:00:24 UTC] PHP Warning:  mysqli::__construct(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in Standard input code on line 22
wordpress_1  |
wordpress_1  | MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known
wordpress_1  | [03-Jan-2020 16:00:27 UTC] PHP Warning:  mysqli::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in Standard input code on line 22
wordpress_1  | [03-Jan-2020 16:00:27 UTC] PHP Warning:  mysqli::__construct(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in Standard input code on line 22
```
