### ISSUE TITLE
fpm versions don't work

### ISSUE THREAD

**Issue by hyperknot** [docker-library/wordpress#467]
I am following the official sample docker compose yml, in a totally clean environment, I delete my `/data` folders before running `docker-compose up`.

My problem is that if I use the normal, non-fpm image everything works perfectly. However if I use the fpm one, the web server doesn't return anything:

```
curl http://localhost:8080
curl: (52) Empty reply from server
```

Here is my docker-compose.yml:
```
version: "3.7"
services:

  wp:
    image: wordpress:fpm
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 1
    volumes:
      - "/data/wp/data:/var/www/html"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: "wp"
    volumes:
      - "/data/mysql/data:/var/lib/mysql"
```
