### ISSUE TITLE
image doesn't startup correctly using `fig up`

### ISSUE THREAD

**Issue by skoblenick** [docker-library/wordpress#47]
This may not be supported but none the less. I have boot2docker 1.4.1 installed on OS X Yosemite. I also have fig 1.0.1 installed.

It looks like the WordPress image makes the assumption that the link to mysql is available at the time the container loads and exits immediately with a failure if it isn't. I assume the mysql client is attempting to setup the databases for first launch to save the user the trouble from doing this, however this makes the assumption the service/application has already been started when in reality WordPress itself doesn't require the database created for 'installation'. It is required for 'configuration' and 'usage', both steps that could be done once the connection to the db is established (at any time). At the very least the container could make use of the mysqli.reconnect to reestablish the connection when lost.

Steps to reproduce:

0) Create a fig.yml containing:

```
db:
  image: mysql:latest
  ports:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=wordpress
    - MYSQL_PORT_3306_TCP=3306
web:
  image: wordpress:latest
  ports:
    - "8080:80"
  links:
    - db:mysql
  environment:
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_PASSWORD=wordpress
    - WORDPRESS_DB_NAME=wordpress
  expose:
    - "8080"
```

1) Verify no containers are running:
```
$ fig ps
Name   Command   State   Ports 
------------------------------
```
2) Start up the containers (in a detached mode) 
```
$ fig up -d
Creating example_db_1...
Creating example_web_1...
```
3) List the containers
```
$ fig ps
       Name                      Command               State             Ports          
---------------------------------------------------------------------------------------
example_db_1    /entrypoint.sh mysqld            Up       0.0.0.0:49183->3306/tcp 
example_web_1   /entrypoint.sh apache2-for ...   Exit 1 
```
4) Looking at the logs
```
$ fig logs
Attaching to example_web_1, example_db_1
web_1 | WordPress not found in /var/www/html - copying now...
web_1 | Complete! WordPress has been successfully copied to /var/www/html
web_1 | 
web_1 | Warning: mysqli::mysqli(): (HY000/2002): Connection refused in - on line 5
web_1 | MySQL Connection Error: (2002) Connection refused
db_1  | Running mysql_install_db ...
```
5) Relaunch the containers
```
fig up -d
Recreating example_db_1...
Recreating example_web_1...
```
6) Check the processes
```
$fig ps
       Name                      Command               State               Ports              
---------------------------------------------------------------------------------------------
example_db_1    /entrypoint.sh mysqld            Up      0.0.0.0:49184->3306/tcp        
example_web_1   /entrypoint.sh apache2-for ...   Up      0.0.0.0:8080->80/tcp, 8080/tcp 
```
