### ISSUE TITLE
Wrong folder 777 permissions when persisting wp-content only

### ISSUE THREAD

**Issue by iamcryptoki** [docker-library/wordpress#473]
**WHAT HAPPENED**

I have a custom image that inherits from wordpress:5.3.2-apache (see below).

I'm trying to create a non-root Wordpress container and **persist wp-content folder ONLY** _(not the whole Wordpress at /var/www/html)_.

When running the container:

- /var/www/html is set to 777.
- New plugins installed using the dashboard have a folder set to 777.
- New folders automatically created in wp-content and uploads are set to 777.

Tried to chmod /var/www/html in the Dockerfile, but it does nothing.

Folders have proper permissions when persisting /var/www/html _(all Wordpress files)_.

**WHAT YOU EXPECTED TO HAPPEN**

Persist /var/www/html/wp-content ONLY with /var/www/html permission set to 755.

**DOCKERFILE "wpcustom:5.3.2"**

```
FROM wordpress:5.3.2-apache

ENV TZ="Europe/Paris"
RUN cp /usr/share/zoneinfo/${TZ} /etc/localtime

ENV APACHE_SERVER_NAME="localhost" \
    APACHE_RUN_USER="myuser" \
    APACHE_RUN_GROUP="myuser" \
    APACHE_PORT_HTTP="8080" \
    APACHE_PORT_HTTPS="8443" \
    APACHE_LOG_DIR="/var/log/apache2"

RUN groupadd -g 2000 ${APACHE_RUN_GROUP} && \
    useradd -s /bin/bash -u 2000 -g ${APACHE_RUN_GROUP} ${APACHE_RUN_USER};

RUN sed -i 's/Listen 80/Listen ${APACHE_PORT_HTTP}/g' /etc/apache2/ports.conf; \
    sed -i 's/Listen 443/Listen ${APACHE_PORT_HTTPS}/g' /etc/apache2/ports.conf; \
    sed -i 's/:80/:${APACHE_PORT_HTTP}/g' /etc/apache2/sites-enabled/000-default.conf; \
    sed -i 's/#ServerName www.example.com/ServerName ${APACHE_SERVER_NAME}/g' /etc/apache2/sites-enabled/000-default.conf;

USER ${APACHE_RUN_USER}

EXPOSE ${APACHE_PORT_HTTP} ${APACHE_PORT_HTTPS}

CMD ["apache2-foreground"]
```

**HOW TO REPRODUCE IT**

Using Docker:

```
$ docker run --name wp -v ./wp-content:/var/www/html/wp-content -p 80:8080 -p 443:8443 wpcustom:5.3.2
$ docker exec -i -t wp /bin/bash
$ ls -la /var/www
```

**Note: you can also reproduce it with the original image wordpress:5.3.2-apache.**

Using Kubernetes:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-wordpress
  namespace: dev
  labels:
    app: school
spec:
  selector:
    matchLabels:
      app: school
      role: frontend
      tier: wordpress
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: school
        role: frontend
        tier: wordpress
    spec:
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
      volumes:
        - name: school-wordpress
          persistentVolumeClaim:
            claimName: school-wordpress
      containers:
        - name: school-wordpress
          image: customwp:5.3.2
          imagePullPolicy: Always
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: school-wordpress
              mountPath: /var/www/html/wp-content
          ports:
            - name: liveness
              containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: liveness
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 5
          livenessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: liveness
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 5
          envFrom:
            - configMapRef: { name: school-wordpress }
            - secretRef: { name: school-wordpress }
          env:
            - name: APACHE_SERVER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
```

`$ kubectl exec -it school-wordpress -n dev -- ls -la /var/www`

Thank you!

**Comment by iamcryptoki** [comment]
#6

**Comment by iamcryptoki** [comment]
[issue]( #6)

**Comment by wglambert** [comment]
You want `/var/www/html` to have 775 permissions? It's a volume in the Dockerfile so it can't be modified without mounting a folder on top of it to overwrite it.
There's also this workaround https://github.com/docker-library/wordpress/issues/232#issuecomment-420767663

```dockerfile
FROM wordpress:5.3.2-php7.2-apache
RUN mkdir -p /var/www/test/ \
        && chown www-data:www-data /var/www/test \
        && find /etc/apache2 -name '*.conf' -type f -exec sed -ri -e 's!/var/www/html!/var/www/test!g' -e 's!Directory /var/www/!Directory /var/www/test!g' '{}' +
RUN chmod 775 /var/www/test
WORKDIR /var/www/test
```

Checking permissions on the folder
```console
$ docker run -it --rm wordpress:test bash
root@7d62bcadb014:/var/www/test# ls -al
total 8                                                                                                                                                       
drwxrwxr-x 2 www-data www-data 4096 Feb 28 18:39 .                                                                                                            
drwxr-xr-x 6 root     root     4096 Feb 28 18:47 ..
```

Mounting `wp-content` to the new directory `/var/www/test/`
```yaml
version: '3.1'
  
services:

  wordpress:
    image: wordpress:test
    restart: always
    ports:
      - 8080:80
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    user: 1000:1000
    environment:
      APACHE_RUN_USER: '#1000'
      APACHE_RUN_GROUP: '#1000'
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wp-content:/var/www/test/wp-content

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
```

However I am getting a `permission denied Cannot open: No such file or directory` from the entrypoint now


```console
$ mkdir wp-content && chown 1000:1000 wp-content && chmod 777 wp-content

$ docker-compose up -d
Creating network "wordpress1_default" with the default driver
Creating wordpress1_wordpress_1 ... done
Creating wordpress1_db_1        ... done

$ docker-compose logs -f
[. . .]
wordpress_1  | tar: ./wp-admin: Cannot mkdir: Permission denied
wordpress_1  | tar: ./wp-admin/options.php: Cannot open: No such file or directory
wordpress_1  | tar: ./wp-admin: Cannot mkdir: Permission denied
wordpress_1  | tar: ./wp-admin/customize.php: Cannot open: No such file or directory
wordpress_1  | tar: ./wp-admin: Cannot mkdir: Permission denied
wordpress_1  | tar: ./wp-admin/link-add.php: Cannot open: No such file or directory
wordpress_1  | tar: ./wp-admin: Cannot mkdir: Permission denied
wordpress_1  | tar: ./wp-admin/custom-background.php: Cannot open: No such file or directory
wordpress_1  | tar: ./wp-cron.php: Cannot open: Permission denied
wordpress_1  | tar: ./wp-links-opml.php: Cannot open: Permission denied
wordpress_1  | tar: ./wp-blog-header.php: Cannot open: Permission denied
wordpress_1  | tar: ./wp-trackback.php: Cannot open: Permission denied
wordpress_1  | tar: ./xmlrpc.php: Cannot open: Permission denied
wordpress_1  | tar: ./readme.html: Cannot open: Permission denied
wordpress_1  | tar: ./wp-signup.php: Cannot open: Permission denied
wordpress_1  | tar: ./index.php: Cannot open: Permission denied
wordpress_1  | tar: ./license.txt: Cannot open: Permission denied
wordpress_1  | tar: Exiting with failure status due to previous errors
```
