### ISSUE TITLE
Setting `WP_HOME` and `WP_SITEURL` doesn't work

### ISSUE THREAD

**Issue by tomkcook** [docker-library/wordpress#475]
I'm using `wordpress:latest` as of today (image hash is `126aa00ecc0c`).

I'm trying to install wordpress as a site subdirectory (ie under `example.com/blog`).  I've set up nginx to reverse proxy `/blog` to the wordpress container, which has its port 80 exposed to localhost as port 4000.  I've set `WORDPRESS_CONFIG_EXTRA` to:

```
               define('WP_HOME','http://powermyev.co.uk/blog');
               define('WP_SITEURL','http://powermyev.co.uk/blog');
```
When I load `powermyev.co.uk/blog`, it redirects (correctly) to `powermyev.co.uk/blog/wp-admin/install.php`.  But this then endlessly redirects to itself.

Is there a way to get this working?

Here is the relevant bit of the logs from the docker container:

```
45.152.28.120 - - [02/Mar/2020:13:03:47 +0000] "GET /blog HTTP/1.0" 302 374 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
45.152.28.120 - - [02/Mar/2020:13:03:47 +0000] "GET /blog/wp-admin/install.php HTTP/1.0" 302 374 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
45.152.28.120 - - [02/Mar/2020:13:03:47 +0000] "GET /blog/wp-admin/install.php HTTP/1.0" 302 374 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
45.152.28.120 - - [02/Mar/2020:13:03:47 +0000] "GET /blog/wp-admin/install.php HTTP/1.0" 302 374 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
45.152.28.120 - - [02/Mar/2020:13:03:47 +0000] "GET /blog/wp-admin/install.php HTTP/1.0" 302 374 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
45.152.28.120 - - [02/Mar/2020:13:03:47 +0000] "GET /blog/wp-admin/install.php HTTP/1.0" 302 374 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
45.152.28.120 - - [02/Mar/2020:13:03:47 +0000] "GET /blog/wp-admin/install.php HTTP/1.0" 302 374 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
45.152.28.120 - - [02/Mar/2020:13:03:47 +0000] "GET /blog/wp-admin/install.php HTTP/1.0" 302 374 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
45.152.28.120 - - [02/Mar/2020:13:03:47 +0000] "GET /blog/wp-admin/install.php HTTP/1.0" 302 374 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
45.152.28.120 - - [02/Mar/2020:13:03:47 +0000] "GET /blog/wp-admin/install.php HTTP/1.0" 302 374 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
45.152.28.120 - - [02/Mar/2020:13:03:47 +0000] "GET /blog/wp-admin/install.php HTTP/1.0" 302 374 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
```

Here is the docker-compose I'm using:

```
version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: <redacted>
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: <redacted>

   wordpress:
     image: wordpress:latest
     depends_on:
       - db
     ports:
       - "127.0.0.1:4000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: <redacted>
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_CONFIG_EXTRA: |
               define('WP_HOME','http://powermyev.co.uk/blog');
               define('WP_SITEURL','http://powermyev.co.uk/blog');

volumes:
    db_data: {}
```
