### ISSUE TITLE
where can I find php.ini file?

### ISSUE THREAD

**Issue by siddjain** [docker-library/wordpress#482]
I am working with `wordpress:php7.4-fpm-alpine`. I cannot find the `php.ini` file in the container:

```
bash-5.0# find . -name php.ini
```

Where is it? I need to change the maximum upload size supported by wordpress.

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/blob/master/php/README.md#configuration

```console
$ docker run -it --rm wordpress bash

root@409834ea36a4:/var/www/html# ls $PHP_INI_DIR/       
conf.d  php.ini-development  php.ini-production

root@409834ea36a4:/var/www/html# ls $PHP_INI_DIR/conf.d/
docker-php-ext-bcmath.ini   docker-php-ext-mysqli.ini   error-logging.ini
docker-php-ext-exif.ini     docker-php-ext-opcache.ini  opcache-recommended.ini
docker-php-ext-gd.ini       docker-php-ext-sodium.ini
docker-php-ext-imagick.ini  docker-php-ext-zip.ini
```

**Comment by rgolea** [comment]
@wglambert I'm new to wordpress/php/docker in general but I have one small question: How do I extend the php variables?

I am following issue #10 but it's not working for me. 
I have my `uploads.ini` in `$PHP_INI_DIR/conf.d/` and it looks like the following:
```
memory_limit 256M
max_input_time 180
max_input_vars 5000
```
I am not sure if the problem is that I am using variables inside `uploads.ini` that aren't supposed to go there or that there is no `php.ini` file at all.
In my `php -i` command I get the following:
```
Loaded Configuration File => (none)
memory_limit => 128M => 128M
max_input_time => -1 => -1
max_input_vars => 1000 => 1000
```
And my `docker-compose.yml` file looks like this:
```
wordpress:
    image: wordpress:php7.4-apache
    ports:
      - 8080:8080
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=exampleuser
      - WORDPRESS_DB_PASSWORD=examplepass
      - WORDPRESS_DB_NAME=exampledb
    volumes:
      - ./wordpress:/var/www/html
```

Any ideas? Thanks in advance
