### ISSUE TITLE
Kubernetes: How to enable SoapClient?

### ISSUE THREAD

**Issue by DavidCamelo** [docker-library/wordpress#518]
I have the following configuration to deploy wordpress in my kubernetes cluster, I need to enable the PHP soap client extension. how can I do it?

```yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-php-config
  labels:
    app: wordpress
data:
  uploads.ini: |-
    file_uploads = On
    upload_max_filesize = 256M
    post_max_size = 256M
    memory_limit = 64M
    max_execution_time = 600
    max_input_time = 600
```

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-pv-claim
        - configMap:
            defaultMode: 420
            name: wordpress-php-config
          name: php-config
      containers:
        - name: wordpress
          image: wordpress:5.4.2-php7.4-apache
          ports:
            - name: wordpress
              containerPort: 80
              protocol: TCP
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-mysql-pass
                  key: password
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
            - mountPath: /usr/local/etc/php/conf.d/uploads.ini
              name: php-config
              subPath: uploads.ini
          imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
```
