### ISSUE TITLE
The suggested volume for wordpress prevents an update

### ISSUE THREAD

**Issue by dcbCIn** [docker-library/wordpress#520]
In the example stack.yml for wordpress (from https://hub.docker.com/_/wordpress) the volume suggested (wordpress:/var/www/html) prevents an update from the image. Even when the image is updated there is no difference in the 
system since all files are the same.

Shouldn't be another folder for the volume? Something like /var/www/html/wp-content?

```
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
```
