### ISSUE TITLE
wp-json routes returning 404

### ISSUE THREAD

**Issue by Axiol** [docker-library/wordpress#531]
I just added a Wordpress container to my `docker-compose.yml` with this config:

```
wordpress:
  image: wordpress:5.5.1-php7.4-apache
  environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: wordpressUser
    WORDPRESS_DB_PASSWORD: wordpressPass
    WORDPRESS_DB_NAME: wordpress
  ports:
    - 8081:80
  volumes:
    - ./wordpress/plugins:/var/www/html/wp-content/plugins
    - ./wordpress/themes:/var/www/html/wp-content/themes
  depends_on: 
    - db
```

Everything starts well, all seems fine. Until I try to access `/wp-json` routes. Everything return a 404. And when I check the health section, there is indeed an error for the REST API:

```
Erreur : cURL error 7: Failed to connect to localhost port 8081: Connection refused (http_request_failed)
```

Anybody have an idea why the container would not be able to connect to himself?
