### ISSUE TITLE
Can't create directories in the wp-content/

### ISSUE THREAD

**Issue by Trane9991** [docker-library/wordpress#534]
Here in Dockerfile https://github.com/docker-library/wordpress/blob/master/php7.4/fpm/Dockerfile#L88 directories are being pre-created, to set permissions on the folders for future mounts.

I wanted to add one more folder `cache`. But it was mysteriously gone from the container.

For example image like:
```dockerfile
FROM wordpress:5.5.1-php7.4-fpm 
RUN mkdir /var/www/html/wp-content/cache/ && ls -al /var/www/html/wp-content/
RUN ls -al /var/www/html/wp-content/
```

Resulted in the following build log:
```
Step 1/3 : FROM wordpress:5.5.1-php7.4-fpm
 ---> 58a200fd0768
Step 2/3 : RUN mkdir /var/www/html/wp-content/cache/ && ls -al /var/www/html/wp-content/
 ---> Running in 68905758cdcf
total 20
drwxrwxrwx 5 www-data www-data 4096 Oct  8 13:18 .
drwxrwxrwx 3 www-data www-data 4096 Oct  8 13:18 ..
drwxr-xr-x 2 root     root     4096 Oct  8 13:18 cache
drwxrwxrwx 2 www-data www-data 4096 Sep 11 09:12 plugins
drwxrwxrwx 2 www-data www-data 4096 Sep 11 09:12 themes
Removing intermediate container 68905758cdcf
 ---> a1e985c4ad25
Step 3/3 : RUN ls -al /var/www/html/wp-content/
 ---> Running in 4ab957561104
total 16
drwxrwxrwx 4 www-data www-data 4096 Oct  8 13:18 .
drwxrwxrwx 3 www-data www-data 4096 Oct  8 13:18 ..
drwxrwxrwx 2 www-data www-data 4096 Sep 11 09:12 plugins
drwxrwxrwx 2 www-data www-data 4096 Sep 11 09:12 themes
Removing intermediate container 4ab957561104
 ---> a22fb6ca6c36
Successfully built a22fb6ca6c36
```

You can see, that on the step 2 directory `cache` is present, but on step 3 it is missing.
Apparently, this is a known bug https://github.com/moby/moby/issues/3639.

Just wanted to leave this here for other people, or maybe we can come upon some better approach to pre-create some directories.

**Comment by tianon** [comment]
This would be because `/var/www/html` is a defined `VOLUME` in the base image (as you've determined, but just to be clear).

If you instead pre-create `/usr/src/wordpress/wp-content/cache`, then any new container should create `/var/www/html` at runtime when it copies `/usr/src/wordpress` over to `/var/www/html` to pre-heat the Wordpress installation.

**Comment by Trane9991** [comment]
> If you instead pre-create `/usr/src/wordpress/wp-content/cache`, then any new container should create `/var/www/html` at runtime when it copies `/usr/src/wordpress` over to `/var/www/html` to pre-heat the Wordpress installation.

Thanks for the quick reply!

I tried that approach, however, this doesn't solve the permissions problem because docker volumes are mounted on container start wit `root:root` permission. Then, when `docker-entrypoint.sh` executed and it tries to copy `/usr/src/wordpress/wp-content/cache` to `/var/www/html/wp-content/cache` directory already exists there so permissions are not being applied as well :( 

My current workaround for that is wrapping the `docker-entrypoint.sh` script with following code:
```
RUN echo "#!/bin/bash" > /docker-entrypoint.sh \
    && echo "chown -v www-data:www-data /var/www/html/wp-content/*" >> /docker-entrypoint.sh \
    && echo 'source docker-entrypoint.sh' >> /docker-entrypoint.sh \
    && chmod 755 /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["php-fpm"]
```

this way permissions are enforced on container start.

**Comment by wglambert** [comment]
With proper permissions I don't encounter any issues with mounting the folder to `/usr/src/wordpress/wp-content/cache`

```console
$ mkdir cache && echo test > cache/test_file && chmod -R 755 cache

$ docker-compose up -d
Creating network "test_default" with the default driver
Creating volume "test_wordpress" with default driver
Creating volume "test_db" with default driver
Creating test_db_1        ... done
Creating test_wordpress_1 ... done

$ docker exec test_wordpress_1 ls -l wp-content
total 4
drwxr-xr-x 2 www-data www-data 23 Oct  8 17:22 cache
-rw-r--r-- 1 www-data www-data 28 Jan  8  2012 index.php
drwxr-xr-x 3 www-data www-data 55 Sep  1 18:54 plugins
drwxr-xr-x 5 www-data www-data 88 Sep  1 18:54 themes

$ docker exec test_wordpress_1 ls -l wp-content/cache
total 4
-rwxr-xr-x 1 www-data www-data 5 Oct  8 17:22 test_file
```

<details>
<summary> docker-compose.yml </summary>

```yaml
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - /test/cache:/usr/src/wordpress/wp-content/cache

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
```

</details>

**Comment by Trane9991** [comment]
Hey @wglambert , my use-case is a bit different.

I'm running wordpress on ECS with shared EFS filesystem mounted to the `/var/www/html/wp-content`.
However, EFS is quite slow for frequent reads. So I'm mounting `wp-content/plugins`, `wp-content/themes` and `wp-content/cache` as docker volumes for faster reads.

Now consider the following

<details>
  <summary> docker-compose.yml </summary>


```yaml
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - wordpress-cache:/var/www/html/wp-content/cache

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  wordpress-cache:
  db:
```
</details>

Then lets simulate some behavior of w3tc plugin which tries to create the `wp-content/cache/tmp` directory:
```sh
$ docker exec -it -u www-data tmp_wordpress_1 mkdir /var/www/html/wp-content/cache/tmp
mkdir: cannot create directory '/var/www/html/wp-content/cache/tmp': Permission denied
```
