### ISSUE TITLE
docker:latest is HTTPS ready ?

### ISSUE THREAD

**Issue by VGzsysadm** [docker-library/wordpress#553]
docker-compose.yml
```
version: '3.9'
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:443"
    environment:
      - WORDPRESS_DB_USER=
      - WORDPRESS_DB_NAME=
      - WORDPRESS_TABLE_PREFIX=
      - WORDPRESS_DB_PASSWORD=
      - WORDPRESS_DB_HOST=
    networks:
      - wordpress
    volumes:
      - wordpress_vol:/var/www/html/wp-content:rw
    container_name: wordpress
networks:
  wordpress:
    external: true
volumes:
  wordpress_vol:
    external: true
```

Dockerfile

```
FROM wordpress:latest
COPY ./certs /etc/ssl/
ADD ./default-ssl.conf /etc/apache2/sites-available/
RUN a2enmod ssl && a2ensite default-ssl.conf
```

default-ssl.conf

```
<VirtualHost *:443>
        ServerName mysite.com
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        SSLEngine on
        SSLCertificateFile /etc/ssl/certificate.pem
        SSLCertificateKeyFile /etc/ssl/certificate.key
        SSLCertificateChainFile /etc/ssl/certificate.ca.crt
</VirtualHost>
```

Apache2 server allways return

Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.
Apache/2.4.38 (Debian) Server at mysite.com Port 80

using HTTP works as expected, is this image ready for https ?

Thanks

kind regards
