### ISSUE TITLE
Bind mounting custom .htaccess file not allowed / possible

### ISSUE THREAD

**Issue by lfleuren** [docker-library/wordpress#559]
In order to configure a Wordpress Multisite setup I have been using docker bind mounts to inject a custom .htaccess file into a container. 

docker compose file fragment:

```yaml
    volumes:
      - type: bind
        source: /opt/custom_htaccess
        target: /var/www/html/.htaccess
```
Due to moving the .htaccess file to the Dockerfile a new problem arises when starting the service. It is not able to start because the .htaccess untar process fails.

wordpress_multisite.llaz7a57a6id@vps01    | tar: ./.htaccess: Cannot open: File exists
wordpress_multisite.llaz7a57a6id@vps01    | tar: Exiting with failure status due to previous errors

I prefer to use default Wordpress images, so I am wondering what would be the best solution.
