### ISSUE TITLE
error with database connection

### ISSUE THREAD

**Issue by xavierartot** [docker-library/wordpress#565]
I'm using Mac OS 11 and desktop Docker.
I followed the guide: https://docs.docker.com/compose/wordpress/
When I'm trying to connect to browser :
http://localhost:8000
Then, I have this error: 
Error establishing a database connection

I don't have error ?

What can I do from here?

```
➜  docker-wordpress docker --version
Docker version 20.10.2, build 2291f61
```

```
➜  docker-wordpress docker-compose up -d
docker-wordpress_db_1 is up-to-date
docker-wordpress_wordpress_1 is up-to-date
```

```
➜  docker-wordpress cat docker-compose.yml
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: root
       MYSQL_PASSWORD: root

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
```

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/wordpress#-via-docker-stack-deploy-or-docker-compose

Your variables don't match, the `WORDPRESS_DB` ones need to correspond to the database's variables
```yaml
WORDPRESS_DB_HOST: db
WORDPRESS_DB_USER: root
WORDPRESS_DB_PASSWORD: root
WORDPRESS_DB_NAME: wordpress
```
