### ISSUE TITLE
2MB file limit

### ISSUE THREAD

**Issue by chongma** [docker-library/wordpress#570]
Hi,
I am having trouble changing the 2MB limit of the wordpress image.

I have tried adding the following to docker-compose.yaml
```yaml
volumes:
  - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
```
with the uploads.ini in the same folder as docker-compose.yaml containing the following
```ini
file_uploads = On
memory_limit = 64M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 600
```
it gets listed with strange permissions

```bash
# ls -al /usr/local/etc/php/conf.d/
ls: cannot access '/usr/local/etc/php/conf.d/uploads.ini': Permission denied
total 48
drwxr-xr-x. 1 root root 4096 Mar  7 17:48 .
drwxr-xr-x. 1 root root 4096 Aug  6  2020 ..
-?????????? ? ?    ?       ?            ? uploads.ini
-rw-r--r--. 1 root root   20 Aug  7  2020 docker-php-ext-bcmath.ini
-rw-r--r--. 1 root root   18 Aug  7  2020 docker-php-ext-exif.ini
-rw-r--r--. 1 root root   16 Aug  7  2020 docker-php-ext-gd.ini
-rw-r--r--. 1 root root   21 Aug  7  2020 docker-php-ext-imagick.ini
-rw-r--r--. 1 root root   20 Aug  7  2020 docker-php-ext-mysqli.ini
-rw-r--r--. 1 root root   82 Aug  7  2020 docker-php-ext-opcache.ini
-rw-r--r--. 1 root root   20 Aug  6  2020 docker-php-ext-sodium.ini
-rw-r--r--. 1 root root   17 Aug  7  2020 docker-php-ext-zip.ini
-rw-r--r--. 1 root root  331 Aug  7  2020 error-logging.ini
-rw-r--r--. 1 root root  150 Aug  7  2020 opcache-recommended.ini
```
this is the only way i have found and it is strange it doesn't work in my case

**Comment by chongma** [comment]
i also tried adding the following to docker-compose.yml
```yaml
WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD','direct');
        @ini_set( 'upload_max_size' , '20M' );
        @ini_set( 'post_max_size', '13M');
        @ini_set( 'memory_limit', '15M' );
```
the lines were in the wp-config.php but it made no difference to upload size limit

**Comment by wglambert** [comment]
Your variable is typo'd `@ini_set( 'upload_max_size'`, should be `@ini_set( 'upload_max_filesize'`

See also https://github.com/docker-library/wordpress/issues/375#issuecomment-463303796 and https://github.com/docker-library/wordpress/issues/10#issuecomment-66906071

**Comment by chongma** [comment]
@wglambert thanks, i changed that typo and ensured it was in my wp-config.php.  but i still have a 2MB file limit.

**Comment by wglambert** [comment]
I think you want those in the `php.ini`? Or a separate one will do, as shown in the examples I linked to it will work

**Comment by chongma** [comment]
yes as i said in my original comment i copied an uploads.ini to /usr/local/etc/php/conf.d/ but it seems like the permissions are all wrong.  not sure why it isn't working in my case as a lot of other people seem to have it working.

my current full yaml.  i am not doing anything special
```yaml
version: '3.1'
services:
  wordpress:
    image: wordpress
    restart: always    
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_TABLE_PREFIX: $WORDPRESS_TABLE_PREFIX
    #   WORDPRESS_AUTH_KEY:
    #   WORDPRESS_SECURE_AUTH_KEY:
    #   WORDPRESS_LOGGED_IN_KEY:
    #   WORDPRESS_NONCE_KEY:
    #   WORDPRESS_AUTH_SALT:
    #   WORDPRESS_SECURE_AUTH_SALT:
    #   WORDPRESS_LOGGED_IN_SALT:
    #   WORDPRESS_NONCE_SALT:
    #   WORDPRESS_DEBUG:
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD','direct');
        @ini_set( 'upload_max_filesize' , '20M' );
        @ini_set( 'post_max_size', '13M');
        @ini_set( 'memory_limit', '15M' );
    ports:
      - '3070:80'
    volumes:
      - $VOLUME_PATH:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - mariadb-docker_backend
networks:
  mariadb-docker_backend:
    external: true
```

**Comment by wglambert** [comment]
I'm not able to reproduce

```console
$ docker-compose up -d
Creating network "root_default" with the default driver
Creating root_wordpress_1 ... done
Creating root_db_1        ... done

$ docker exec root_wordpress_1 php -i 2>&1 | grep upload_max_filesize
upload_max_filesize => 64M => 64M
@ini_set('upload_max_filesize','20M' );
@ini_set('upload_max_filesize','20M' );
@ini_set('upload_max_filesize','20M' );
```

I'm not sure of the specific formatting for `WORDPRESS_CONFIG_EXTRA`, maybe it doesn't work for these options... but the `*.ini` does

<details>
<summary> docker-compose.yml & uploads.ini </summary>

```yaml
$ cat docker-compose.yml 
version: '3.1'
services:
  wordpress:
    image: wordpress
    restart: always    
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD','direct');
        @ini_set('upload_max_filesize','20M' );
        @ini_set('post_max_size','13M');
        @ini_set('memory_limit','15M');
    ports:
      - '3070:80'
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
```

uploads.ini
```ini
file_uploads = On
memory_limit = 64M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 600
```

</details>
