### ISSUE TITLE
docker-compose file on docker hub not working

### ISSUE THREAD

**Issue by JoeTac** [docker-library/wordpress#585]
I copied the  docker file provided [here](https://github.com/docker-library/docs/tree/master/wordpress#-via-docker-stack-deploy-or-docker-compose) and added the _depends_on_.

I wait for the all images to complete and when I go to http://localhost:8080, I get a **Error establishing a database connection**

Am I missing something?

Here is the file:
```
version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
  db:
```

**Comment by wglambert** [comment]
I'm not able to reproduce, you may have tried connecting too quickly before the database was initialized

**Comment by JoeTac** [comment]
> I'm not able to reproduce, you may have tried connecting too quickly before the database was initialized

How long did you wait? I waited for about 10-15min after it said it was running.

**Comment by wglambert** [comment]
On the hardware I was using I made the initial connection after a minute. What do the `docker-compose logs` show?

If you want a quick external environment you can use https://labs.play-with-docker.com to test this

**Comment by JoeTac** [comment]
I found an alternative docker-compose file that is working (and has phpmyadmin). Thanks!

```
version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '7081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '7080:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
```
