### ISSUE TITLE
wp-config unable to get env variables from Gitlab

### ISSUE THREAD

**Issue by AxelDenhaut** [docker-library/wordpress#612]
Hey everyone !
I'm working on a website that use Wordpress - Docker, and since I'm trying to update the website, I've encountered an issue with the wp-config file. 
I can't get environnement variables to work.
It was working like a charm before updating to wordpress 5.7, and the new method to manage wp-config (with the getenv_docker function)
I'm not using any secrets to manage my database credentials, I'm just passing variables through a gitlab-ci file (I get credentials variable from GitLab)
In the log, I'm getting this : 
`No 'wp-config.php' found in /var/www/html, but 'WORDPRESS_...' variables supplied; copying 'wp-config-docker.php'`

Is there anything to do with these variables ? 
I'm passing the variables in the job that way : 
```
- env | grep WORDPRESS > .env
- docker run --env-file=.env --name wpbuild wordpress:$WP_VERSION apache2-foreground -v
```
And of course I set up every variables to make that work (that was working until the update) : 
 ```
variables:
    WORDPRESS_DB_NAME: $SITENAME
    WORDPRESS_DB_PASSWORD: $DB_PASSWORD
    WORDPRESS_DB_USER: $DB_USER
    WORDPRESS_TABLE_PREFIX: wp_
    WORDPRESS_DB_HOST: localhost
```
As I said, it was working before the update. 
Am I missing something ? 
There's no need to add `_FILE` after my variables name since I'm not using secrets right ? 

I'm a little lost there, I'm not used to docker configuration, but I can't see what's happening here.
