### ISSUE TITLE
No selectable languages during the installer

### ISSUE THREAD

**Issue by Rchtr** [docker-library/wordpress#617]
Hello,

i'm using this docker compose file:
```yaml
version: '3.9'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password 
      WORDPRESS_DB_NAME: database
    volumes:
      - /etc/localtime:/etc/localtime:ro #ro=read only
      - /etc/timezone:/etc/timezone:ro #ro=read only
      - wordpress_data:/var/www/html
    networks:
      backend:
      frontend:
        ipv4_address: XXX.XXX.XX.XXX

volumes:
  wordpress_data:
    name: wordpress_data

networks:
  frontend:
    external:
      name: myNetwork
  backend:
    external:
      name: backend
```

This are the permissions of wp-content:
`drwxr-xr-x  4 www-data www-data  4096 May 13 01:49 wp-content`

This are the subfolders of wp-content after running docker compose up:
`-rw-r--r-- 1 www-data www-data   28 Jan  8  2012 index.php`
`drwxr-xr-x 3 www-data www-data 4096 May 13 01:49 plugins`
`drwxr-xr-x 5 www-data www-data 4096 May 13 01:49 themes`
I guess the folder languages is missing here.

After running wordpress the first time and configuring it, there is no Site Language in General-Settings.
