### ISSUE TITLE
Using a different internal (target) port than 80

### ISSUE THREAD

**Issue by obedparla** [docker-library/wordpress#622]
Hey!

I'm looking for a way to use an internal port other than 80. I've searched everywhere with no result. My config is simple:

```
... maria DB stuff...

mywordpress:
    depends_on:
      - db
    build: .
    ports:
      # I want this to be 8181:8181 (or anything else that isn't 80)
      - 8181:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: define('WP_SITEURL', 'http://mywordpress:8181');
    volumes:
      - ../../:/var/www/html/wp-content/plugins
```

When I try to use ports as ` - 8181:8181` WordPress is not accessible internally anymore on `http://mywordpress:8181`

The reason for this that I have a database backup with hardcoded `'http://mywordpress:8181'` and I want to run the internal WordPress container under the same port to prevent doing find-replace on the database or the likes.

Is this possible using this image? I was looking into implementing a reverse proxy, or maybe modifying the apache config. I'm not the best at Docker so any help would be appreciated.

**Comment by wglambert** [comment]
Providing a custom `ports.conf` is probably the simplest method, mounted at `/etc/apache2/ports.conf`

Ports.conf
```apache
# If you just change the port or add more ports here, you will likely also
# have to change the VirtualHost statement in
# /etc/apache2/sites-enabled/000-default.conf

Listen 8181

<IfModule ssl_module>
        Listen 443
</IfModule>

<IfModule mod_gnutls.c>
        Listen 443
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

```yaml
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8181:8181
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - ./ports.conf:/etc/apache2/ports.conf

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
```

```console
$ docker-compose up -d
Creating network "wordpress_default" with the default driver
Creating volume "wordpress_wordpress" with default driver
Creating volume "wordpress_db" with default driver
Creating wordpress_db_1        ... done
Creating wordpress_wordpress_1 ... done

$ docker ps
CONTAINER ID   IMAGE       COMMAND                  CREATED              STATUS              PORTS                                               NAMES
1aeb2cfed951   wordpress   "docker-entrypoint.s…"   About a minute ago   Up About a minute   80/tcp, 0.0.0.0:8181->8181/tcp, :::8181->8181/tcp   wordpress_wordpress_1
b48cc4126ea6   mysql:5.7   "docker-entrypoint.s…"   About a minute ago   Up About a minute   3306/tcp, 33060/tcp                                 wordpress_db_1

$ docker exec -it wordpress_wordpress_1 bash
root@1aeb2cfed951:/var/www/html# apt update &>/dev/null && apt install -y net-tools &>/dev/null
root@1aeb2cfed951:/var/www/html# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8181            0.0.0.0:*               LISTEN      1/apache2
tcp        0      0 127.0.0.11:45687        0.0.0.0:*               LISTEN      -
udp        0      0 127.0.0.11:41764        0.0.0.0:*                           -
```
