### ISSUE TITLE
WordPress latest tag does not parse environment variables correctly

### ISSUE THREAD

**Issue by thijsvanloef** [docker-library/wordpress#625]
Hello, while testing with the new `latest` WordPress (5.8) I noticed the environment variables not being parsed correctly resulting in a `Error establishing a database connection` error. 

![image](https://user-images.githubusercontent.com/58031337/126636720-96a3b717-e4d1-46e4-b4e3-cae4431e74f3.png)

### Steps to Reproduce

1. Pull the `wordpress:latest` image
2. Create a `docker-compose.yml` file based on the [official documentation](https://hub.docker.com/_/wordpress)
3. Change the environment variables from the WordPress service
```yaml
version: '3.1'

services:

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: THIS_SHOULD_APPEAR
      WORDPRESS_DB_USER: THIS_SHOULD_APPEAR
      WORDPRESS_DB_PASSWORD: THIS_SHOULD_APPEAR
      WORDPRESS_DB_NAME: THIS_SHOULD_APPEAR
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: THIS_SHOULD_APPEAR
      MYSQL_USER: THIS_SHOULD_APPEAR
      MYSQL_PASSWORD: THIS_SHOULD_APPEAR
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
```
4. Startup the docker-compose with `docker-compose up -d`
5. Enter the wordpress container with `docker exec -it wordpress_container bash`
6. Look inside the wp-config.php file: `cat wp-config.php`

### Expected Result
```php
**/ ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define( 'DB_NAME', getenv_docker('WORDPRESS_DB_NAME', 'THIS_SHOULD_APPEAR') );

/** MySQL database username */
define( 'DB_USER', getenv_docker('WORDPRESS_DB_USER', 'THIS_SHOULD_APPEAR') );

/** MySQL database password */
define( 'DB_PASSWORD', getenv_docker('WORDPRESS_DB_PASSWORD', 'THIS_SHOULD_APPEAR') );

/**
 * Docker image fallback values above are sourced from the official WordPress installation wizard:
 * https://github.com/WordPress/WordPress/blob/f9cc35ebad82753e9c86de322ea5c76a9001c7e2/wp-admin/setup-config.php#L216-L230
 * (However, using "example username" and "example password" in your database is strongly discouraged.  Please use strong, random credentials!)
 */

/** MySQL hostname */
define( 'DB_HOST', getenv_docker('WORDPRESS_DB_HOST', 'THIS_SHOULD_APPEAR') );

/** Database charset to use in creating database tables. */
define( 'DB_CHARSET', getenv_docker('WORDPRESS_DB_CHARSET', 'utf8') );

/** The database collate type. Don't change this if in doubt. */
define( 'DB_COLLATE', getenv_docker('WORDPRESS_DB_COLLATE', '') );
**
```

### Actual Result
```php
**/ ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define( 'DB_NAME', getenv_docker('WORDPRESS_DB_NAME', 'wordpress') );

/** MySQL database username */
define( 'DB_USER', getenv_docker('WORDPRESS_DB_USER', 'example username') );

/** MySQL database password */
define( 'DB_PASSWORD', getenv_docker('WORDPRESS_DB_PASSWORD', 'example password') );

/**
 * Docker image fallback values above are sourced from the official WordPress installation wizard:
 * https://github.com/WordPress/WordPress/blob/f9cc35ebad82753e9c86de322ea5c76a9001c7e2/wp-admin/setup-config.php#L216-L230
 * (However, using "example username" and "example password" in your database is strongly discouraged.  Please use strong, random credentials!)
 */

/** MySQL hostname */
define( 'DB_HOST', getenv_docker('WORDPRESS_DB_HOST', 'mysql') );

/** Database charset to use in creating database tables. */
define( 'DB_CHARSET', getenv_docker('WORDPRESS_DB_CHARSET', 'utf8') );

/** The database collate type. Don't change this if in doubt. */
define( 'DB_COLLATE', getenv_docker('WORDPRESS_DB_COLLATE', '') );
**
```
