### ISSUE TITLE
WordPress docker ignore all env variables !

### ISSUE THREAD

**Issue by RedJohn14** [docker-library/wordpress#637]
Hello,

I have used the original config from hub.docker.com

https://hub.docker.com/_/wordpress?tab=description&page=1&ordering=last_updated&name=php8.0-fpm-alpine

```
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: test
      WORDPRESS_DB_NAME: test
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
```

After docker containers started I visit localhost:8080 and get **Error establishing a database connection.**

I have a quick look in the wp-config.php and see that config is not correct set:

```
// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define( 'DB_NAME', getenv_docker('WORDPRESS_DB_NAME', 'wordpress') );

/** MySQL database username */
define( 'DB_USER', getenv_docker('WORDPRESS_DB_USER', 'example username') );

/** MySQL database password */
define( 'DB_PASSWORD', getenv_docker('WORDPRESS_DB_PASSWORD', 'example password') );
```

A second check inside the container with **printenv** looks like this:

```
root@5483d265734a:/var/www/html# printenv
HOSTNAME=5483d265734a
PHP_VERSION=7.4.23
APACHE_CONFDIR=/etc/apache2
PHP_INI_DIR=/usr/local/etc/php
GPG_KEYS=42670A7FE4D0441C8E4632349E4FDC074A4EF02D 5A52880781F755608BF815FC910DEB46F53EA312
PHP_LDFLAGS=-Wl,-O1 -pie
PWD=/var/www/html
HOME=/root
PHP_SHA256=cea52313fcffe56343bcd3c66dbb23cd5507dc559cc2e3547cf8f5452e88a05d
WORDPRESS_DB_HOST=db
PHPIZE_DEPS=autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c
TERM=xterm
PHP_URL=https://www.php.net/distributions/php-7.4.23.tar.xz
PHP_EXTRA_CONFIGURE_ARGS=--with-apxs2 --disable-cgi
SHLVL=1
PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
WORDPRESS_DB_PASSWORD=test
APACHE_ENVVARS=/etc/apache2/envvars
WORDPRESS_DB_USER=test
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
WORDPRESS_DB_NAME=testb
PHP_EXTRA_BUILD_DEPS=apache2-dev
PHP_ASC_URL=https://www.php.net/distributions/php-7.4.23.tar.xz.asc
PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
_=/usr/bin/printenv
```

All variables are available inside the container. But not merged with the config!

How can I used the env variables now? Because this is also your official manual on hub.docker.com!

Regards!
