### ISSUE TITLE
I am unable to override the upload_max_filesize

### ISSUE THREAD

**Issue by Temepest74** [docker-library/wordpress#653]
I copy pasted the docker-compose.yml file you provided. I tried to override the upload_max_filesize but with no luck
The content of uploads.ini
```
upload_max_filesize = 16M
post_max_size = 16M
```
docker-compose.yml
```
version: '3.3'

services:

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 1
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
 ```
If i run this comman `sudo docker-compose up -d` and then, I run this command to check the upload_max_filesize `sudo docker exec wordpress_wordpress_1 php -i | grep upload` I get this output
```
file_uploads => On => On
max_file_uploads => 20 => 20
upload_max_filesize => 2M => 2M
upload_tmp_dir => no value => no value
session.upload_progress.cleanup => On => On
session.upload_progress.enabled => On => On
session.upload_progress.freq => 1% => 1%
session.upload_progress.min_freq => 1 => 1
session.upload_progress.name => PHP_SESSION_UPLOAD_PROGRESS => PHP_SESSION_UPLOAD_PROGRESS
session.upload_progress.prefix => upload_progress_ => upload_progress_
```
as you can see, the value didn't change. This is confirmed inside wordpress wp-admin/upload.php page
```
