### ISSUE TITLE
Apache 403 Forbidden on wp-admin

### ISSUE THREAD

**Issue by oxr463** [docker-library/wordpress#678]
> Forbidden
>
> You don't have permission to access this resource.
> Apache/2.4.38 (Debian) Server at wordpress.com Port 80

URL: http://wordpress.com/wp-admin/

```
version: '3.1'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt/:/etc/letsencrypt
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: always
  wordpress:
    container_name: wordpress
    image: wordpress:5.6.1-php7.3-apache
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: bar
      WORDPRESS_DB_PASSWORD: baz
      WORDPRESS_DB_NAME: foo
    volumes:
      - wordpress:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: foo
      MYSQL_USER: bar
      MYSQL_PASSWORD: baz
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    command: --max_allowed_packet=500M
volumes:
  wordpress:
  db:
```
