### ISSUE TITLE
Minimal example causing empty page response, when changing PHP from 8.0 to 8.1

### ISSUE THREAD

**Issue by DJviolin** [docker-library/wordpress#682]
If I upgrade from `wordpress:5.8.3-php8.0-apache` to `wordpress:5.8.3-php8.1-apache`, I'm getting an empty webpage visiting Wordpress' URL in the browser. I use Docker for Windows:

```yaml
version: '3.9'

services:

  db:
    image: mariadb:10.7.1-focal
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
    volumes:
      - 'db-data:/var/lib/mysql'

  wordpress:
    depends_on:
      - db
    image: wordpress:5.8.3-php8.1-apache
    # image: wordpress:5.8.3-php8.0-apache
    ports:
      - '${WP_ENV_PORT:-8080}:80'
    networks:
      - frontend
      - backend
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
    volumes: &ref_0
      - >-
       wp-data:/var/www/html

networks:
  frontend:
  backend:

volumes:
  db-data: {}
  wp-data: {}
```

```sh
$ docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:44:07 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$ docker-compose --version
Docker Compose version v2.2.3

$ systeminfo
...
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
...
```
