### ISSUE TITLE
DOCS: Upgrade gudiance?

### ISSUE THREAD

**Issue by scyto** [docker-library/wordpress#689]
I am new to wordpress, very familiar with docker containers / compose / stacks etc.

I got my WordPress network-multisite install running on docker, its served by an nginx reverse proxy.
Got all that working (though docs could be better because as there too many contradictory, invalid or just outdated blog posts on docker-wordpress+nginx)

My www, plugins and themes are all mounted as a bind mount from my host via the volume directive in compose

```
volumes: 
  - /mnt/iscsi/docker/wordpress/www:/var/www/html
```

When I choose to update to from 5.8.x to 5.9 is the right way to run the upgrade inside the container or pull the 5.9 image and do docker-compose down then up?

**Comment by scyto** [comment]
for reference, my full stack
```
version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - /mnt/iscsi/docker/wordpressdb_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: xxxxxx
       MYSQL_DATABASE: wordpressdb
       MYSQL_USER: xxxxx
       MYSQL_PASSWORD: xxxxxx
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == manager]


   wordpress:
     image: wordpress:latest
     ports:
       - 8080:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: xxxxxx
       WORDPRESS_DB_PASSWORD: xxxxxxxx
       WORDPRESS_DB_NAME: wordpressdb
     volumes:
       - /mnt/iscsi/docker/wordpress/www:/var/www/html
      
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == manager]

volumes:
    db_data:
```
