### ISSUE TITLE
docker-compose + 5.8.3-php8.1-apache

### ISSUE THREAD

**Issue by hertell** [docker-library/wordpress#692]
The php8.1 package seems to be broken. It throws the following error with the docker-compose.yml file

`wordpress-wordpress-1  | [Thu Feb 03 12:09:15.246976 2022] [php:error] [pid 60] [client 1.2.3.4:51063] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'wpdb.wp_options' doesn't exist in /var/www/html/wp-includes/wp-db.php:2056\nStack trace:\n#0 /var/www/html/wp-includes/wp-db.php(2056): mysqli_query(Object(mysqli), 'SELECT option_v...')\n#1 /var/www/html/wp-includes/wp-db.php(1945): wpdb->_do_query('SELECT option_v...')\n#2 /var/www/html/wp-includes/wp-db.php(2581): wpdb->query('SELECT option_v...')\n#3 /var/www/html/wp-includes/functions.php(1734): wpdb->get_var('SELECT option_v...')\n#4 /var/www/html/wp-includes/load.php(752): is_blog_installed()\n#5 /var/www/html/wp-settings.php(159): wp_not_installed()\n#6 /var/www/html/wp-config.php(133): require_once('/var/www/html/w...')\n#7 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')\n#8 /var/www/html/wp-admin/install.php(36): require_once('/var/www/html/w...')\n#9 {main}\n  thrown in /var/www/html/wp-includes/wp-db.php on line 2056, referer: http://foo.bar.tld:8888/`

All works normal with 5.8.3-php8.0-apache

Below the content of my docker-compose.yml

```
version: "3.1"

services:
    wordpress:
      image: "wordpress:5.8.3-php8.1-apache"
      depends_on:
            - "mysql"
      ports:
          - "8888:80"
      environment:
          WORDPRESS_DB_HOST: "mysql"
          WORDPRESS_DB_NAME: "wpdb"
          WORDPRESS_DB_USER: "wpuser"
          WORDPRESS_DB_PASSWORD: "foobar"
      volumes:
        - ./volumes/html:/var/www/html

    mysql:
        image: "mariadb:10.6"
        environment:
            MYSQL_ROOT_PASSWORD: "example"
            MYSQL_USER: "wpuser"
            MYSQL_DATABASE: "wpdb"
            MYSQL_PASSWORD: "foobar"

        volumes:
            - ./volumes/db:/var/lib/mysql


```
