### ISSUE TITLE
data inside /var/www/html is getting override

### ISSUE THREAD

**Issue by nishit93-hub** [docker-library/wordpress#694]
Hi There,

I am creating my own docker image from image` WordPress`

```
FROM WordPress
COPY . /var/www/html
```
When I run the custom image on Kubernetes, whatever I copied data in the docker image gets overridden.
If logs it shows

```
WordPress not found in /var/www/html - copying now...
Complete! WordPress has been successfully copied to /var/www/html
```

**Comment by wglambert** [comment]
If `index.php` and `wp-includes/version.php` don't exist then "WordPress doesn't appear to be installed"

https://github.com/docker-library/wordpress/blob/1b7873367ec93d971105aa21a54185d889bbbee3/latest/php8.1/apache/docker-entrypoint.sh#L28-L37

**Comment by nishit93-hub** [comment]
@wglambert 
But I am copying  index.php and wp-includes/version.php to /var/www/html while creating docker image.
Actually, I am downloading the latest WordPress from wget `https://wordpress.org/latest.tar.gz `and copying everything inside that under the HTML directory.

**Comment by nishit93-hub** [comment]
@wglambert 

Yes if I run my custom docker image from docker then it works fine, there it doesn't install WordPress. However, if run the same image on Kubernetes then it installs the WordPress there.

**Comment by nishit93-hub** [comment]
This is my manifest file

```
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
    type: frontend
spec:
  selector:
    app: wordpress
    type: frontend
  ports:
  - name: http-sv-port 
    port: 80
    targetPort: http-port
  - name: https-sv-port
    port: 443
    targetPort: https-port
  type: NodePort 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: px-file-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
    type: frontend
spec:
  selector:
    matchLabels:
      app: wordpress
      type: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        type: frontend
    spec:
      containers:
        - name: wordpress
          image: nishit2408/wordpress-demo:3.0
          ports:
            - containerPort: 80
              name: http-port
            - containerPort: 443
              name: https-port
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-service
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbuser
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbpassword
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbname
          volumeMounts:
            - name: wordpress-vol
              mountPath: /var/www/html
      volumes:
        - name: wordpress-vol
          persistentVolumeClaim:
            claimName: wp-pv-claim

```

```
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: wordpress
    type: database
spec:
  selector:
    app: wordpress
    type: database
  ports:
  - port: 3306
    targetPort: db-port
  type: ClusterIP 
---
apiVersion: v1
data:
  dbname: d29yZHByZXNz
  dbpassword: cGFzc3dvcmQxMjM0
  dbrootpassword: cm9vdDEyMzQ=
  dbuser: dXNlcl93b3JkcHJlc3M=
kind: Secret
metadata:
  creationTimestamp: null
  name: mariadb-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: px-db-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: wordpress
    type: database
spec:
  selector:
    matchLabels:
      app: wordpress
      type: database
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        type: database
    spec:
      containers:
        - name: wordpress
          image: bitnami/mariadb:latest
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"         
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbuser
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbname
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbpassword 
          volumeMounts:
            - name: mariadb-vol
              mountPath: /bitnami/mariadb
      volumes:
        - name: mariadb-vol
          persistentVolumeClaim:
            claimName: mysql-pv-claim     
```

**Comment by nishit93-hub** [comment]
If I use the image in above manifest and deploy the WordPress then it install wordpress again there

**Comment by wglambert** [comment]
Your `mountPath` is overwriting that directory. I can't find where it says that in the k8s docs but yeah, it does that
```yaml
volumeMounts:
            - name: wordpress-vol
              mountPath: /var/www/html
```
And any reason for downloading https://wordpress.org/latest.tar.gz and hardcoding it in a Dockerfile when the Dockerfile already has it in `/usr/src/wordpress` (which is what's getting copied to `/var/www/html` if an existing install isn't detected)

https://github.com/docker-library/wordpress/blob/1b7873367ec93d971105aa21a54185d889bbbee3/latest/php8.1/apache/Dockerfile#L124-L131

Also `storage: 1Gi` seems kind of small
