### ISSUE TITLE
TTFB very slow

### ISSUE THREAD

**Issue by Fossil01** [docker-library/wordpress#715]
I don't know where to look, I normally run WP in a VM using nginx and PHP-FPM but for a new small site I decided to run it in Docker on our Docker Swarm cluster.

The website is extremely slow, checking the devtools the TTFB sometimes takes up to 5s. I have tried adding `:caching` to the volume mounts but that has no effect.

`Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1`

```
version: '3.8'

services:
  www:
    image: wordpress:php8.1
    environment:
      WORDPRESS_DB_HOST: REMOVED
      WORDPRESS_DB_USER: REMOVED
      WORDPRESS_DB_PASSWORD: REMOVED
      WORDPRESS_DB_NAME: REMOVED
    volumes:
      - /mnt/shared/containers/REMOVED/data/wp-content:/var/www/html/wp-content:cached
      - /mnt/shared/containers/REMOVED/wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
    deploy:
      replicas: 3
      update_config:
        order: start-first
      rollback_config:
        order: start-first
```

I have also tried adding custom opcache config via the wordpress.ini mount:

```
[opcache]
opcache.enable=1
opcache.max_wasted_percentage=10
opcache.revalidate_freq=0
opcache.validate_timestamps=1
opcache.max_accelerated_files=7963
opcache.memory_consumption=192
opcache.interned_strings_buffer=16
opcache.fast_shutdown=1
```

but it's still very slow. The ` /mnt/shared/containers` directory is a GlusterFS volume but that shouldn't matter. I also have an ancient Joomla container running in the same way which is now slow at all (PHP 5.6 + Nginx).

Any tips?
