### ISSUE TITLE
Unable to use networks using docker-compose file

### ISSUE THREAD

**Issue by myszalay** [docker-library/wordpress#718]
Hi Team,

I am using a docker compose file like stack.yml for Wordpress and Mysql. It's working as expected.
By default It creates a network called **wordpress_default.**
When I am trying to add my own created bridged network using the network option, it is just not working.
It connects always to the **wordpress_default** network. 
Same when trying to add a proper container name.
Would someone point me right direction?

Thanks
Laszlo

**Example:**
```
version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: database  
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork
```
