### ISSUE TITLE
Add support for WP_ENVIRONMENT_TYPE

### ISSUE THREAD

**Issue by pfefferle** [docker-library/wordpress#733]
WordPress does support environment types since version 5.5  https://developer.wordpress.org/reference/functions/wp_get_environment_type/ 

It would be nice to add support for `WP_ENVIRONMENT_TYPE` as environment variable.

**Comment by pfefferle** [comment]
It is already possible using:

```YAML
version: '3'
services:
  wordpress:
    image: wordpress:latest
    environment:
      WP_ENVIRONMENT_TYPE: development
```

:)
