### ISSUE TITLE
Problems with updates and theme installations on version 6.0.2

### ISSUE THREAD

**Issue by fedegibut** [docker-library/wordpress#742]
I opened this thread to talk to the author of the Wordpress image.

I use this docker compose setup:

```
  wordpress:
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=...
      - WORDPRESS_DB_USER=...
      - WORDPRESS_DB_PASSWORD=...
      - WORDPRESS_DB_NAME=...
    volumes:
      - ./wordpress:/var/www/html/
```

I have two problems:

1) Docker files are not accessible after starting the project in Compose;
2) Wordpress asks me for the FTP parameters that I don't have when I'm locally. It is necessary to resort to the Linux OS hosting Docker and physically edit a Wordpress php file to solve.

**How do you solve these 2 problems?**
