### ISSUE TITLE
WORDPRESS_CONFIG_EXTRA is not evaluated

### ISSUE THREAD

**Issue by juliankrieger** [docker-library/wordpress#771]
I've read #557 , #332 and #142 because the content of my `WORDPRESS_CONFIG_EXTRA` file does not seem to be evaluated. To check for this, I throw fatal errors in the code that should normally be evaluated, but I can see no such error in my error logs. Is this behaviour broken again?

Things I tried:

- Deleting my images and rebuilding them entirely
- Opening a terminal into my wordpress-blog container and deleting wp-config

Docker-Compose File:

```
version: '3.4'

x-common-variables: &common-variables
  FSHM_HOST: *******
  MYSQL_DATABASE: *******
  MYSQL_USER: ******
  MYSQL_PASSWORD: ******
  MYSQL_ROOT_PASSWORD: ******
  WORDPRESS_TABLE_PREFIX: *******
  WORDPRESS_DB_HOST: db
  DEVELOPMENT_DATABASE: ********
  DEVELOPMENT: true

services:

  wordpress:
    depends_on:
      - db  
    container_name: wordpress-blog
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      <<: *common-variables
      WORDPRESS_DB_USER: ******
      WORDPRESS_DB_PASSWORD: *******
      WORDPRESS_DB_NAME: *******
      WORDPRESS_DB_CHARSET: utf8
      WORDPRESS_DB_COLLATE: ''
      WORDPRESS_AUTH_KEY: ******
      WORDPRESS_SECURE_AUTH_KEY: *******
      WORDPRESS_LOGGED_IN_KEY: ******
      WORDPRESS_NONCE_KEY: ******
      WORDPRESS_AUTH_SALT: *****
      WORDPRESS_SECURE_AUTH_SALT: ******
      WORDPRESS_LOGGED_IN_SALT: ******
      WORDPRESS_NONCE_SALT: ******
      WORDPRESS_CONFIG_EXTRA: |
        $$is_development = getenv_docker('DEVELOPMENT', false) == 'true' ? true : false;
        trigger_error("$$is_development", E_USER_ERROR); // just to check if evaluation works in the first place
        if($$is_development) {
          define('WORDPRESS_DB_NAME', getenv_docker('DEVELOPMENT_DATABASE', 'fsweb_development'));
        }
    volumes:
      - type: bind
        source: ./wordpress/wp-content
        target: /var/www/html/wp-content
    tmpfs:
      - /tmp
      - /run

  db:  
    container_name: mysql-db
    image: mysql:5.7
    restart: always
    environment: *common-variables
    volumes:
      - type: bind
        source: ./database_content/mysql
        target: /var/lib/mysql

```
