### ISSUE TITLE
pre-run instructions

### ISSUE THREAD

**Issue by funivan** [docker-library/wordpress#795]
Sometimes we have to run WP CLI or other tools to configure instance. It would be nice to have something like this in the docker-entry
```sh
if [[ -f "/usr/local/bin/pre-run.sh" ]]; then
 /usr/local/bin/pre-run.sh
fi
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["apache2-foreground"]
```
WDYT about adding these lines into the `docker-entrypoint.sh`

**Comment by saenglert** [comment]
When trying to wrap the commands like this, I receive the following error:
```
/usr/local/bin/docker-entrypoint.sh: line 99: exec: sh -c 'my-docker-entrypoint.sh && exec apache2-foreground': not found
```

Any further tips?

**Comment by tianon** [comment]
Can you give the exact line you ran? (`docker run ...` or your `command:` section in Compose YAML, for example)

**Comment by saenglert** [comment]
Service description in my compose file:
```
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
    - db
```
The corresponding Dockerfile:
```
FROM wordpress:6-php8.2-apache

COPY certs/* /etc/apache2/certs/
COPY ssl/local-ssl.conf /etc/apache2/sites-enabled/
COPY php.conf/* /usr/local/etc/php/conf.d/

# Enable SSL
RUN a2enmod ssl && service apache2 restart

# Overwrite the images script with our own, so it also sets custom envs
COPY --chown=www-data:www-data wp-config-docker.php /usr/src/wordpress/

# Add our own entrypoint script
COPY my-docker-entrypoint.sh /usr/local/bin/

CMD ["sh -c 'my-docker-entrypoint.sh && exec apache2-foreground'"]
```
Thank you for your help!
