### ISSUE TITLE
Images in upload does not show up when using FPM image

### ISSUE THREAD

**Issue by Pshemas** [docker-library/wordpress#826]
I'm trying to set up a WP instance without apache. As a proxy I use Caddy. Thus I'd prefer to not use main images as I'd be running proxy with proxy - which makes no sense.

I've tried fpm image - while it started it resulted in issues during use. For instance images from the wp-content/uploads/year/month do not show up. 
I've checked permissions, tried changing them (even to pretty unsafe values) but that didn't help.
Any ideas what can be an issue, what can I check next?

Also - is there a non-fpm image that wouldn't contain apache?

Currently I'm using this compose file :

```
version: '3.3'
services:
  # Database
  database:
    image: mysql:latest
    container_name: database
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    env_file: 
      - .env
    environment: 
      MYSQL_DATABASE: blog_wp
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - blog-network
  # Wordpress
  wordpress:
    depends_on:
      - database
    image: wordpress:fpm-alpine
    container_name: wordpress
    restart: always
    user: "root:root"
    env_file: 
      - .env
    environment:
      - WORDPRESS_DB_HOST=database:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=blog_wp
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./wordpress:/var/www/html
    networks:
      - blog-network
  # Webserver
  caddy:
    image: caddy:alpine
    container_name: webserver
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - blog-network
networks:
  blog-network:
    driver: bridge
```

and Caddyfile looks like this:

```
somedomain {
        root * /var/www/html
        php_fastcgi wordpress:9000
        file_server
}
```

**Comment by tianon** [comment]
I'm not able to reproduce: :sweat_smile:

![image](https://github.com/docker-library/wordpress/assets/161631/76a72239-48f2-47e4-bb5c-3a18ca94977a)

I made some pretty minimal changes to your example in order to reproduce on my local system (mostly removing things, nothing truly transformative):

```yaml
version: '3.3'
services:
  database:
    image: mysql:8
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_USER: example
      MYSQL_PASSWORD: CHANGE-THIS-BEFORE-USE-OMG
      MYSQL_DATABASE: blog_wp
    command: '--default-authentication-plugin=mysql_native_password'
  wordpress:
    image: wordpress:fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: example
      WORDPRESS_DB_PASSWORD: CHANGE-THIS-BEFORE-USE-OMG
      WORDPRESS_DB_NAME: blog_wp
    volumes:
      - ./wordpress:/var/www/html
  caddy:
    image: caddy:alpine
    ports:
      - 8888:80
    volumes:
      - ./wordpress:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
```

```Caddyfile
:80 {
        root * /var/www/html
        php_fastcgi wordpress:9000
        file_server
}
```
