### ISSUE TITLE
Mapping /var/www/html to existing wp folder

### ISSUE THREAD

**Issue by tubia** [docker-library/wordpress#84]
Hi all,  
I created a docker-compose file to make the images work taking an existing wordpress folder that is on my home.  
Here is the docker-compose.yml

``` yaml
wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 8082:80
  environment:
    WORDPRESS_DB_USER: test
    WORDPRESS_DB_PASSWORD: test
    WORDPRESS_DB_NAME: test
  volumes:
     - /home/tubia/test/:/var/www/html

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_DATABASE: test
    MYSQL_USER: test
    MYSQL_PASSWORD: test
```

This results in the installation page, when I visit `localhost:8082`, so it is not taking the volume as configured. Also If I enter the container with `docker exec -ti wp_container /bin/bash` and `ls` the `/var/www/html`, it's a standard default wp installation, not the one I mapped with the volume.

Hints? It is the expected behaviour?

**Comment by yosifkit** [comment]
Does `/home/tubia/test` contain `index.php` and `wp-includes/version.php`?  If those exist, then we do not try to copy the default wordpress source. If those do not exist and `/var/www/html` is not empty we do print a warning and sleep for 10 seconds ([`entrypoint.sh`](https://github.com/docker-library/wordpress/blob/master/docker-entrypoint.sh#L37-L42))

**Comment by tubia** [comment]
Hi @yosifkit thank for the explanation, now it's clear.  
In fact, linking `/home/tubia/test/wp-content` with `/var/www/html/wp-content` works. I imagine the reason for this choice but what about, for example, a custom `.htaccess` ?  
Actually I'm experiencing an issue related  to the URL (I changed in the backend the siteURL from the IP to the current domain name). Yes, it's off-topic, but just to show that maybe with files in other directories there could be problems (or maybe I don't understand well the correct path).

**Comment by yosifkit** [comment]
You could use volumes for the single file `/my/.htaccess:/var/www/html/`.  You should be able to use your full wordpress directory directly mounted into the container `/var/www/html/` if your directory has all of the wordpress files like `index.php` and `wp-includes/`.

**Comment by pierreozoux** [comment]
@tubia did it solve your issue? If yes, can you close please? Thanks :)

**Comment by ailic** [comment]
> You could use volumes for the single file /my/.htaccess:/var/www/html/.

@yosifkit I'm experiencing the problem with achieving what you've said. Like @tubia I have no problems with mounting folders, that works just fine. But when it's about files, no solution yet to make it work.

Here's my **docker-compose.yml** file:
```yml
web:
  image: wordpress
  ports:
    - "80:80"
  volumes:
    - ./src/wordpress/wp-content:/var/www/html/wp-content
    - ./src/wordpress/wp-config.php:/var/www/html/wp-config.php
  environment:
    WORDPRESS_DB_NAME: dummyname
  links:
    - db:mysql
db:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - mysql-data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: dummypass
```
After **docker-compose up** (or even **docker run** command) I get an error:
```
WordPress not found in /var/www/html - copying now...
WARNING: /var/www/html is not empty - press Ctrl+C now if this is an error!
+ ls -A
wp-config.php
+ sleep 10
Complete! WordPress has been successfully copied to /var/www/html
sed: couldn't edit wp-config.php: not a regular file
```
With this line removed ```    - ./src/wordpress/wp-config.php:/var/www/html/wp-config.php``` everything works fine.

**Comment by pierreozoux** [comment]
@ailic you should open an other issue.
In your specific case, if `wp-config.php` is not created before starting, docker (in previous version, it is no longer the case) would create a folder, and not a file. (Now, with latest version, you'll just get an error).

**Comment by jpswade** [comment]
I've been trying to get this to work using docker-compose in my existing Wordpress directory, but no matter what I seem to do, I always get this message:

`WordPress not found in /var/www/html - copying now...`

I suspect that, for whatever reason the default mapping to the working directory isn't working.

**Comment by tianon** [comment]
@jpswade can you share your `docker-compose.yml` contents?

**Comment by jpswade** [comment]
Sure...

https://gist.github.com/jpswade/b6af225e50fccbd0dce7cf054b13778d

**Comment by bfreeds** [comment]
Hi all, 

I'm experiencing a similar issue here, regarding the mounted volume still bringing me to a fresh install page.  Here are my details - please let me know if there's other info that would help replicate / understand what's going on here.

My directory structure:  
- docker-compose.yml
- **wordpress** (complete backup of WP-Engine install)  
  - ...
  - index.php
  - wp-config.php (has info to connect to ./wp-content/mysql.sql dump)
  - ...
  - **wp-admin**
  - **wp-content**
    - mysql.sql
    - ...
  - **wp-includes**
    - version.php
    - ...

docker-compose.yml looks like this:
```dockerfile
version: '2'  
services:  
  db:  
    image: mysql:5.7
    #  this will load existing database into mysql container on startup
    volumes:
      - ./wordpress/wp-content/test_db.sql:/docker-entrypoint-initdb.d/test_db.sql
    environment:  
      MYSQL_DATABASE: [existing db name]
      MYSQL_ROOT_PASSWORD: test
    container_name: mysql
    restart: always
  wordpress:   
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      #  mount the wordpress install into container
      - ./wordpress:/var/www/html
    environment:
      #  get a message that this is required for connecting to mysql, but it seems to overwrite wp-config.php
      WORDPRESS_DB_PASSWORD: test
    container_name: wordpress
    ports: 
      - 8080:80
    links:
      - db
    
```

My understanding (from [this](https://forums.docker.com/t/how-to-port-an-existing-wordpress-site-to-a-docker-container/4860) discussion) is that when the "wordpress" container initializes and sees that wordpress is included in the container's /var/www/html the container's initialization script should not use environment variables to connect to the database.

The issue I'm having is that the wordpress container does not locate the database that has been initialized in the Mysql container.  What then happens is every time I go to localhost:8080 I'm presented with the dialogue for installing a fresh install of Wordpress.  

I'm also noticing in the `wordpress/wp-config.php`, after `docker-compose up` these fields get overwritten from the existing exported settings to this:  
```php
define( 'DB_NAME', 'wordpress');
define( 'DB_USER', 'root');
define( 'DB_PASSWORD', 'test');
define( 'DB_HOST', 'mysql');
```

Thanks all in advance for helping figure this out - and the work being done on the official image.  After I finally can get this working I'd be happy to submit a pull request with documentation for replicating an existing site through Docker (I've found this aspect here and on the mysql import process to be a little scattered).

**Comment by yosifkit** [comment]
@bfreeds, if you already have a wordpress install then there is nothing that the wordpress entrypoint gives you except the changing of your `wp-config.php` file based upon environment variables.  Just add an `entrypoint: apache2-foreground` in the yaml to skip the default entrypoint script.

**Comment by bfreeds** [comment]
Thanks @yosifkit , that's a great tip, though I'm still having some connectivity issues between containers.  Using the above `docker-compose.yml` file, adding `entrypoint: apache2-foreground`, I get a 500 internal server error when hitting localhost:8080.

![screen shot 2016-07-14 at 9 54 04 am](https://cloud.githubusercontent.com/assets/5316367/16841836/005c5dfc-49a9-11e6-84ca-cce007b6665f.png)

If WordPress is mounted with a full install, how should the MySQL container be configured to appropriately connect to the WP container?  What is the relationship between the MySQL environment variables set (`MYSQL_ROOT_PASSWORD, MYSQL_USER, MYSQL_DATABASE`) to the settings in `wp-config.php`?  Does the MYSQL_ROOT_PASSWORD need to match `define( 'DB_PASSWORD', 'test');`?

Sorry if this is basic or redundant, I'm new to Docker and WordPress and trying to get a good understanding of how these things are working.

**Comment by yosifkit** [comment]
Yes, the config in the `wp-config` file needs to match the setup of your database.  In the compose file above, you called the MySQL container `db` with a name of `mysql`; either value can be used as the `DB_HOST` value in `wp-config`.  As for `DB_NAME`, `DB_USER`, and `DB_PASSWORD`, they need to be set so that the WordPress container can connect as a valid user in your MySQL database supplying a correct password and using the correct database name.

Editing site code for WordPress (like posts and pages), is not a simple task to backup and move to another place (since the siteurl used in links stored in the text is based upon the url that it is first accessed on), but there are wordpress plugins that could be useful.

**Comment by twelch555** [comment]
@brfeeds I'm also new to docker and am working on a similar type of setup. I do notice that your docker-compose file is version 2 but you don't have a primary level volume declaration. Version 2 of the docker-compose format introduced an evolved way of handling volumes and networks. I got stung by that looking at blogs and instructions written in the V1 docker-compose format.

The other thing you may find handy is the [local-persist](https://github.com/CWSpear/local-persist) volume driver. I'm finding that it is smoothing out dealing with volumes generally.

**Comment by tianon** [comment]
Closing since the original issue here appears to be solved (plus several others).

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!

**Comment by huraji** [comment]
I have similar issue but I'm not sure if this is caused by redis and mariadb. Basically my existing folders, plugins and theme are not copied in docker, nor the database. Here is my `docker-compose.yml`:

```
version: '3'

services:
  db:
    container_name: database
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d/wordpress.sql:/docker-entrypoint-initdb.d/wordpress.sql
    restart: always

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
    links: 
      - db
    restart: always
    environment:
      DB_HOST: db:3306
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on: 
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_ROOT_PASSWORT: wordpress
      
  redis:
    image: redis:latest
    container_name: redis
```

I get just a fresh installation process.
