### ISSUE TITLE
Swarm stack deploy cant find secrets "The system cannot find the file specified"

### ISSUE THREAD

**Issue by moxieproxy** [docker-library/wordpress#840]
Using the [official docker documentation for secrets](https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose), I am unable to run a swarm stack (single node) with error The system cannot find the file specified. 

Using this exact compose file from the docs and running:

`docker swarm init` 
`docker stack deploy --compose-file docker-compose.yml app`

docker-compose.yml:

```
services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_root_password
       - db_password

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_password


secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

volumes:
    db_data:
```

I get the error message "C:\Users\Admin\Projects\wordpress-docker\apps\sites\site1\db_password.txt: The system cannot find the file specified."
