### ISSUE TITLE
Is this malware in wordpress docker image?

### ISSUE THREAD

**Issue by AdamSop** [docker-library/wordpress#846]
I just found something weird, some weird logs and probably crypto miner in try to run Wordpress website using this image wordpress:6.3.1-php8.1-fpm. After few hours of running this website with clean install on clean Ubuntu server, I found this issue.
Wordpress was just installed without any other changes. So here is the docker compose and log images.

```yaml
version: "3.9"

networks:
  wordpress:
    ipam:
      config:
        - subnet: 172.25.0.0/16

services:
  nginx:
    image: nginx:1.15.12
    ports:
        - '8077:80'
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - ./.htpasswd-test:/etc/nginx/.htpasswd-test
        - ./wordpress:/var/www/html
    links:
        - wordpress
    networks:
        - wordpress
    restart: always
  mysql:
    image: mysql:5.7.43
    command: '--default-authentication-plugin=mysql_native_password'
    env_file:
      - .env
    ports:
        - '3304:3306'
    volumes:
        - ./db-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    networks:
      - wordpress
  wordpress:
    image: wordpress:6.3.1-php8.1-fpm
    ports:
        - '9000:9000'
    volumes:
        - ./wordpress:/var/www/html
    env_file:
      - .env
    environment:
        - WORDPRESS_DEBUG=${WORDPRESS_DEBUG}
        - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
        - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
        - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
        - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
        - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    networks:
      - wordpress
    links:
        - mysql
    restart: always
```

![kinsing](https://github.com/docker-library/wordpress/assets/3744848/5eddcf9c-f609-467a-a274-54ac688608d4)

![kinsing2](https://github.com/docker-library/wordpress/assets/3744848/aa76e545-2896-4dd0-9a0f-aa1151fb6216)

I have tested it a few times in the past few days and the outcome is always the same. Kinsing malware files appeared in the docker overlay2 folder inside folders related to the Wordpress container (UpperDir). It does not appear immediately when you run docker container, it appears a few hours later.
