### ISSUE TITLE
Unable to use .user.ini 

### ISSUE THREAD

**Issue by ragnarkarlsson** [docker-library/wordpress#858]
Hi

I'm trying to use Ninjafirewall with the WordPress FPM variant and having trouble. Specifically I'm running multiple Wordpress containers with one nginx reverse proxy.

The Nginx container has volume mapped for /var/www/html which contains all the websites like this:

- /var/www/html/website1/public/<wordpress files>
- /var/www/html/website2/public/<wordpress files>
- /var/www/html/website3/public/<wordpress files>
- etc

Each Wordpress container then has the relevant volume mount for that website to /var/www/html

As a result the Nginx and Wordpress containers have differing file paths, which I thought I had resolved using the appropriate nginx config. However when I try to set up .user.ini to prepend the Ninjafirewall PHP, or indeed their recommended .htninja file for docker container use, the PHP-FPM does not pick up the dotfiles at all.

Running the relevant `docker exec -t website php --info | grep .ini` allows me to see the .user.ini directive is there.

Whilst I could run the Apache variant, that feels heavy handed to me (why run multiple Apache when I'm already fronting it all with Nginx).

Have I missed something obvious? Is the default build of Wordpress docker php-fpm in module mode rather than cgi mode?

Sanitised Docker compose

```
# Nginx
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=website
    volumes:
      - /mnt/logrotate-nginx:/etc/logrotate.d/custom-nginx:ro
      - /mnt/nginx/http.d:/etc/nginx/http.d
      - /mnt/nginx/config:/config
      - /mnt/nginx/logs:/config/log/site-logs
      - /mnt/nginx/site-confs:/config/nginx/site-confs
      - /mnt/nginx/challenges:/var/www/challenges
      - /mnt/websites:/var/www/html
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    labels:
      - "diun.enable=true"
     
website:
    image: wordpress:php8.2-fpm
    container_name: website
    env_file:
      - ./.env.website
    volumes:
      - /mnt/websites/website/public:/var/www/html
      - /mnt/websites/php/upload.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
      - /mnt/websites/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
    restart: unless-stopped
    labels:
      - "diun.enable=true"
```

Sanitised Nginx config

```
server {
    # Ports to listen on
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    include /config/nginx/ssl.website.conf;

    server_name website;

    index index.php;
    root /var/www/html/website/public;

    include /config/global/lets-encrypt.conf;
    include /config/global/http-server-defaults.conf;
    include /config/global/static-files.conf;
    include /config/global/security-headers/permissions-policy-none.conf;

    location ~ [^/]\.php(/|$) {
        try_files $uri /index.php?$args =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_pass website:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        # Overrides logs defined in nginx.conf, allows per site logs.
        access_log /config/log/site-logs/website-access.log standard if=$do_log;
        error_log /config/log/site-logs/website-error.log;
    }

    location / {
       try_files $uri $uri/ /index.php?$args;
       # Overrides logs defined in nginx.conf, allows per site logs.
       access_log /config/log/site-logs/website-access.log standard;
       error_log /config/log/site-logs/website-error.log;
    }
}
# Redirect http to https
server {
    server_name  website;

    listen 80;
    listen [::]:80;

    access_log off;
    error_log /dev/null;

    include /config/global/lets-encrypt.conf;
    include /config/global/http-server-defaults.conf;

    location / {
        return 301 https://website$request_uri;
    }
}
```

*edit to correct the docker compose as had incorrect volume path
