### ISSUE TITLE
BUG: Restarting docker logs users out

### ISSUE THREAD

**Issue by adamchemiawppl** [docker-library/wordpress#895]
Hi,

Not sure it is "expected", or not, but every time I restart/rebuild container, all users get logged out.
I'm running Wordpress with Mariadb and Redis (non-persistent).

Any idea what is the root cause? Is there a chance Redis actually handles login tokens (then restarting it would obviously remove such data, if it is not saved in DB). Then again - it seems with redis plugin disabled the same thing happens.

Any idea what to look for? Couldn't find any ideas on the root cause.

Best regards,
Adam Wojciechowski

**Comment by tianon** [comment]
This is something I've noticed as well, but I never quite figured out exactly what's causing it.

I _think_ it's related to PHP sessions and where they get stored (might need to set `session.save_path` to a persistent location?).

**Comment by adamchemiawppl** [comment]
Well, AFAIK wordpress manages sessions by itself, rather than using php in-built sessions, so I think it shouldn't be related.

**Comment by adamchemiawppl** [comment]
Any chance for additional input from anybody? It is a fairly significant issue, impacting usefulness of this repo.

**Comment by LaurentGoderre** [comment]
I can't reproduce with just Wordpress and MariaDB

**Comment by LaurentGoderre** [comment]
Still not able to reproduce with

```yaml
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CONFIG_EXTRA: define('WP_REDIS_HOST', 'redis');
    volumes:
      - wordpress:/var/www/html

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: exampledb
      MARIADB_USER: exampleuser
      MARIADB_PASSWORD: examplepass
      MARIADB_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  redis:
      image: 'redis:alpine'
      ports:
        - '6379:6379'
      restart: always
      expose:
        - '6379'

volumes:
  wordpress:
  db:
```
