### ISSUE TITLE
mysql container does not export a port to the host

### ISSUE THREAD

**Issue by javaskater** [docker-library/wordpress#931]
* I used the *docker-compose.yml* you propose
  * I only added the port 3307 as an export of port 3306 of mysql8 
```yaml
version: '3.1'

services:

  wordpress:
    image: wordpress
    user: ${UID}
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306 # I added this export
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
```
* I try to access the mysql database from my Ubuntu host using mysql client
```bash
jmena01@M077-1840900:~/CONSULTANT$ mysql -h 127.0.0.1 -P 3306 --protocol=tcp -u exampleuser exampledb -p
Enter password: 
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:3306' (111)
jmena01@M077-1840900:~/CONSULTANT$ mysql -h 127.0.0.1 -P 3307 --protocol=tcp -u exampleuser exampledb -p
Enter password: 
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:3307' (111)
jmena01@M077-1840900:~/CONSULTANT$ mysql -h localhost -P 33060 --protocol=tcp -u exampleuser exampledb -p
Enter password: 
ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost:33060' (111)
```
* in fact no port is exported for the mysql container (see these host commands)
```bash
jmena01@M077-1840900:~/CONSULTANT$ netstat -tln # No 3306 33060 nor 3307
Connexions Internet actives (seulement serveurs)
Proto Recv-Q Send-Q Adresse locale          Adresse distante        Etat      
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN     
tcp6       0      0 :::3389                 :::*                    LISTEN     
tcp6       0      0 :::80                   :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::8080                 :::*                    LISTEN     
tcp6       0      0 ::1:3350                :::*                    LISTEN     
tcp6       0      0 :::5900                 :::*                    LISTEN     
tcp6       0      0 ::1:631                 :::*                    LISTEN
# I ask docker what it exported
jmena01@M077-1840900:~/CONSULTANT$ docker port consultant-db-1 # Nothing exported
jmena01@M077-1840900:~/CONSULTANT$ docker port consultant-wordpress-1 # The 80 port has been exported to 8080
80/tcp -> 0.0.0.0:8080
80/tcp -> [::]:8080
# my containers arejmena01@M077-1840900:~/CONSULTANT$ docker ps
CONTAINER ID   IMAGE       COMMAND                  CREATED          STATUS          PORTS                                   NAMES
3ee77c6a3bad   wordpress   "docker-entrypoint.s…"   13 minutes ago   Up 13 minutes   0.0.0.0:8080->80/tcp, :::8080->80/tcp   consultant-wordpress-1
7ee149e1ddb5   mysql:8.0   "docker-entrypoint.s…"   13 minutes ago   Up 13 minutes   3306/tcp, 33060/tcp                     consultant-db-1 well runnning

```
