### ISSUE TITLE
Update latest to WordPress 6.7.2

### ISSUE THREAD

**Issue by roffel** [docker-library/wordpress#954]
I have created a `docker-compose.yml` file using the `latest` WordPress image. However, this image installs WordPress 6.7.1 instead of WordPress 6.7.2. WordPress 6.7.2 was released to the public on February 11, 2025.

My compose file:
```
version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - 8080:80  # Exposing port 8080 for WordPress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - wordpress_data:/var/www/html  # Persist WordPress data

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example  # Password for the root user
      MYSQL_DATABASE: wordpress     # Database name
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data

volumes:
  wordpress_data:
  db_data:
```

First thing I see after installing:

![Image](https://github.com/user-attachments/assets/05dbec66-2bcf-4b5b-866b-a722155fa9ec)
