### ISSUE TITLE
Docker Multisite Install - getting 'bad reques' from the image?

### ISSUE THREAD

**Issue by scyto** [docker-library/wordpress#957]
I have a multisite install, it was working fine for ages, it is behind a nginx reverse proxy

It can still serve the website www.mydomain.com and blog.mydomain.com

however when I try and access the wp-admin (or heck any url) on mydomain.com i get the following error:

```
Bad Request
Your browser sent a request that this server could not understand.

Apache/2.4.62 (Debian) Server at 10.0.14.6 Port 80
```

this is my stack

```
services:
   db:
     image: mysql:5.7
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD:  redacted
       MYSQL_DATABASE: wordpressdb
       MYSQL_USER: alexb
       MYSQL_PASSWORD: redacted
     deploy:
       mode: replicated
       replicas: 1

   wordpress:
     image: wordpress:latest
     ports:
       - 8080:80
       - 9090:9000
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: redacted
       WORDPRESS_DB_PASSWORD: redacted
       WORDPRESS_DB_NAME: wordpressdb
     extra_hosts:
       - mydomain.com: redactedIP
     volumes:
       - www:/var/www/html
  
     deploy:
       mode: replicated
       replicas: 1

volumes:
  dbdata:
    driver: gluster-vol1
  www:
    driver: gluster-vol1
```

i am fairly certain i don't have an nginx issue as the two main sites are working fine and i am not getting the infinte redirect loop 

i am really not sure where to go from here
