### ISSUE TITLE
Default docker-compose.yml doesn't work

### ISSUE THREAD

**Issue by Zhoros** [docker-library/wordpress#962]
docker-compose.yml content taken from https://hub.docker.com/_/wordpress/
(exact copy paste)

```
services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:

```

logs
```
db-1         | 2025-05-10 19:17:28+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.42-1.el9 started.
wordpress-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
wordpress-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
wordpress-1  | [Sat May 10 19:17:28.643198 2025] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) PHP/8.2.28 configured -- resuming normal operations
wordpress-1  | [Sat May 10 19:17:28.647844 2025] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
db-1         | 2025-05-10 19:17:28+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db-1         | 2025-05-10 19:17:28+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.42-1.el9 started.
db-1         | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
db-1         | 2025-05-10T19:17:29.489107Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
db-1         | 2025-05-10T19:17:29.491957Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.42) starting as process 1
db-1         | 2025-05-10T19:17:29.515791Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db-1         | 2025-05-10T19:17:29.953922Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
db-1         | 2025-05-10T19:17:30.312089Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db-1         | 2025-05-10T19:17:30.313277Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
db-1         | 2025-05-10T19:17:30.317689Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db-1         | 2025-05-10T19:17:30.369601Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
db-1         | 2025-05-10T19:17:30.370883Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.42'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL
```

![Image](https://github.com/user-attachments/assets/7cc8f8ad-61ca-4119-9f68-2b307d1c96a9)
